#!/usr/bin/env bats
# SPDX-License-Identifier: MIT
# Purpose: Contract tests for the support-tier catalog (#1079):
#          scripts/ci/catalog/validate.py and scripts/ci/catalog/render.py.
#
# The first tests run against the live repository; the rest build a
# throwaway repository with one reusable workflow, one plain action and
# detect-changes (whose token scopes the #735 validator derives), so each
# rule is pinned by a case that breaks exactly one thing.

load "../../helpers/common"

VALIDATE="${PROJECT_ROOT}/scripts/ci/catalog/validate.py"
RENDER="${PROJECT_ROOT}/scripts/ci/catalog/render.py"

setup() {
	# PyYAML: system python3 on GitHub-hosted runners, the dev venv locally.
	PY=""
	local candidate
	for candidate in python3 "${PROJECT_ROOT}/.venv/bin/python"; do
		if command -v "${candidate}" >/dev/null 2>&1 && "${candidate}" -c 'import yaml' 2>/dev/null; then
			PY="${candidate}"
			break
		fi
	done
	[[ -n "${PY}" ]] || skip "no python3 with PyYAML (install the dev extra)"
}

_git() {
	git -C "$1" -c user.name=catalog-test -c user.email=catalog-test@example.invalid \
		-c commit.gpgsign=false -c tag.gpgsign=false "${@:2}"
}

# Build the fixture. Its catalog cites the repository's first commit as the
# stable entry's evidence, so ancestry holds at HEAD.
_fixture_root() {
	local root="${BATS_TEST_TMPDIR}/repo"
	mkdir -p "${root}/.github/workflows" "${root}/.github/actions/demo-action" \
		"${root}/.github/actions/detect-changes" "${root}/catalog" "${root}/docs"
	git init -q "${root}"
	_git "${root}" commit -q --allow-empty -m base
	local base
	base="$(git -C "${root}" rev-parse HEAD)"
	cat >"${root}/.github/workflows/reusable-demo.yml" <<'YAML'
---
name: Reusable Demo Workflow
on:
  workflow_call:
    inputs:
      job-name:
        type: string
        default: "Demo Tests"
      runner-image:
        type: string
        default: "ubuntu-24.04"
permissions:
  contents: read
jobs:
  test:
    name: ${{ inputs.job-name }}
    runs-on: ${{ inputs.runner-image }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: echo test
YAML
	cat >"${root}/.github/actions/demo-action/action.yml" <<'YAML'
---
name: Demo action
description: "Do one demo thing. Then explain it at length."
runs:
  using: composite
  steps:
    - run: echo demo
      shell: bash
YAML
	cat >"${root}/.github/actions/detect-changes/action.yml" <<'YAML'
---
name: Detect changes
description: "Map changed paths to filters"
runs:
  using: composite
  steps:
    - run: echo detect
      shell: bash
YAML
	cat >"${root}/catalog/catalog.yml" <<YAML
---
schema-version: 1
fixture-repository: example/consumer-fixture
entries:
  - id: reusable-demo
    kind: reusable-workflow
    tier: stable
    evidence:
      fixture: demo.yml
      last-green: ${base}
      run: https://github.com/example/consumer-fixture/actions/runs/123
    permissions: { contents: read, pull-requests: write }
    runners: [ubuntu-24.04]
    package-managers: [uv]
    prerequisites: ["Commit a uv.lock"]
    limitations: ["Linux only"]
    check-names: ["Demo Tests"]
  - id: demo-action
    kind: composite-action
    tier: preview
    reason: "No external-fixture run yet"
    permissions: { contents: read }
    runners: []
    package-managers: []
    prerequisites: []
    limitations: []
  - id: detect-changes
    kind: composite-action
    tier: internal
    reason: "Used by the demo only"
    permissions: { contents: read, pull-requests: read }
    runners: []
    package-managers: []
    prerequisites: []
    limitations: []
YAML
	cat >"${root}/README.md" <<'MD'
# Demo

Intro stays put.

<!-- BEGIN catalog-index: generated by scripts/ci/catalog/render.py from catalog/catalog.yml; do not edit -->
<!-- END catalog-index -->

Outro stays put.
MD
	"${PY}" "${RENDER}" --write --repo-root "${root}" >/dev/null
	_git "${root}" add -A
	_git "${root}" commit -q -m fixture
	echo "${root}"
}

# Apply a Python edit to the fixture catalog: `data` is the parsed document.
_edit_catalog() {
	local root="$1" code="$2"
	"${PY}" - "${root}/catalog/catalog.yml" "${code}" <<'PY'
import sys, yaml
path, code = sys.argv[1], sys.argv[2]
data = yaml.safe_load(open(path, encoding="utf-8"))
entries = {e["id"]: e for e in data["entries"]}
exec(code)
open(path, "w", encoding="utf-8").write(yaml.safe_dump(data, sort_keys=False))
PY
}

@test "catalog: the repository catalog is consistent" {
	local args=()
	# CI shell-test checkouts are shallow; the "Support Catalog" job fetches
	# full history and runs the ancestry check there.
	if [[ "$(git -C "${PROJECT_ROOT}" rev-parse --is-shallow-repository)" == "true" ]]; then
		args+=(--skip-ancestry)
	fi
	run "${PY}" "${VALIDATE}" "${args[@]}"
	assert_success
	assert_output --partial "OK: catalog/catalog.yml is consistent with the repository"
}

@test "catalog: committed docs/catalog.md and README index match the catalog" {
	run "${PY}" "${RENDER}" --check
	assert_success
	assert_output --partial "OK: generated catalog docs are current"
}

@test "catalog: every public workflow and action in the repository has an entry" {
	local count expected
	count="$(grep -c '^  - id: ' "${PROJECT_ROOT}/catalog/catalog.yml")"
	expected="$(($(find "${PROJECT_ROOT}/.github/workflows" -maxdepth 1 -name 'reusable-*.yml' | wc -l) + \
		$(find "${PROJECT_ROOT}/.github/actions" -mindepth 2 -maxdepth 2 -name action.yml | wc -l)))"
	assert_equal "${count}" "${expected}"
}

@test "catalog: fixture baseline passes with ancestry checked" {
	local root
	root="$(_fixture_root)"
	run "${PY}" "${VALIDATE}" --repo-root "${root}"
	assert_success
	assert_output --partial "NOTICE: 3 entries: 1 stable, 1 preview, 1 internal, 0 deprecated"
}

@test "catalog: a workflow without an entry fails" {
	local root
	root="$(_fixture_root)"
	cp "${root}/.github/workflows/reusable-demo.yml" "${root}/.github/workflows/reusable-extra.yml"
	run "${PY}" "${VALIDATE}" --repo-root "${root}"
	assert_failure
	assert_output --partial "reusable-extra: .github/workflows/reusable-extra.yml has no catalog entry"
}

@test "catalog: an entry without a file and a duplicate entry both fail" {
	local root
	root="$(_fixture_root)"
	_edit_catalog "${root}" '
ghost = dict(entries["demo-action"], id="ghost-action")
data["entries"] += [ghost, dict(entries["demo-action"])]'
	run "${PY}" "${VALIDATE}" --repo-root "${root}"
	assert_failure
	assert_output --partial "ghost-action: no composite-action file for this entry"
	assert_output --partial "demo-action: listed 2 times"
}

@test "catalog: unsorted entries fail" {
	local root
	root="$(_fixture_root)"
	_edit_catalog "${root}" 'data["entries"].reverse()'
	run "${PY}" "${VALIDATE}" --repo-root "${root}"
	assert_failure
	assert_output --partial "entries: must be sorted by kind"
}

@test "catalog: workflow permissions must equal the caller union from the #735 validator" {
	local root
	root="$(_fixture_root)"
	_edit_catalog "${root}" 'entries["reusable-demo"]["permissions"] = {"contents": "read"}'
	run "${PY}" "${VALIDATE}" --repo-root "${root}"
	assert_failure
	assert_output --partial "reusable-demo: \`permissions\` must equal the workflow's caller union {contents: read, pull-requests: write}"
}

@test "catalog: overstated workflow permissions fail too" {
	local root
	root="$(_fixture_root)"
	_edit_catalog "${root}" 'entries["reusable-demo"]["permissions"]["issues"] = "write"'
	run "${PY}" "${VALIDATE}" --repo-root "${root}"
	assert_failure
	assert_output --partial "catalog has {contents: read, issues: write, pull-requests: write}"
}

@test "catalog: an action must cover the scopes the #735 validator derives for it" {
	local root
	root="$(_fixture_root)"
	_edit_catalog "${root}" 'entries["detect-changes"]["permissions"] = {"contents": "read"}'
	run "${PY}" "${VALIDATE}" --repo-root "${root}"
	assert_failure
	assert_output --partial "detect-changes: \`permissions\` must include \`pull-requests: read\`"
}

@test "catalog: an invalid permission level fails" {
	local root
	root="$(_fixture_root)"
	_edit_catalog "${root}" 'entries["demo-action"]["permissions"] = {"contents": "admin"}'
	run "${PY}" "${VALIDATE}" --repo-root "${root}"
	assert_failure
	assert_output --partial "demo-action: invalid permission \`contents: admin\`"
}

@test "catalog: stable without evidence fails" {
	local root
	root="$(_fixture_root)"
	_edit_catalog "${root}" 'del entries["reusable-demo"]["evidence"]'
	run "${PY}" "${VALIDATE}" --repo-root "${root}"
	assert_failure
	assert_output --partial "reusable-demo: tier \`stable\` requires \`evidence\`"
}

@test "catalog: evidence run must be a run URL in the fixture repository" {
	local root
	root="$(_fixture_root)"
	_edit_catalog "${root}" '
entries["reusable-demo"]["evidence"]["run"] = "https://github.com/someone-else/repo/actions/runs/1"'
	run "${PY}" "${VALIDATE}" --repo-root "${root}"
	assert_failure
	assert_output --partial "\`evidence.run\` must be https://github.com/example/consumer-fixture/actions/runs/<id>"
}

@test "catalog: evidence commit must be a full SHA" {
	local root
	root="$(_fixture_root)"
	_edit_catalog "${root}" 'entries["reusable-demo"]["evidence"]["last-green"] = "abc1234"'
	run "${PY}" "${VALIDATE}" --repo-root "${root}"
	assert_failure
	assert_output --partial "\`evidence.last-green\` must be a full 40-character lgtm-ci commit SHA"
}

@test "catalog: evidence from a side branch (a squash-merged PR head) is not an ancestor" {
	local root side
	root="$(_fixture_root)"
	_git "${root}" checkout -q -b pr-head
	_git "${root}" commit -q --allow-empty -m "pr head"
	side="$(git -C "${root}" rev-parse HEAD)"
	_git "${root}" checkout -q -
	_edit_catalog "${root}" "entries['reusable-demo']['evidence']['last-green'] = '${side}'"
	run "${PY}" "${VALIDATE}" --repo-root "${root}"
	assert_failure
	assert_output --partial "is not an ancestor of HEAD"
}

@test "catalog: evidence commit missing from local history fails unless --skip-ancestry" {
	local root
	root="$(_fixture_root)"
	_edit_catalog "${root}" '
entries["reusable-demo"]["evidence"]["last-green"] = "0123456789abcdef0123456789abcdef01234567"'
	run "${PY}" "${VALIDATE}" --repo-root "${root}"
	assert_failure
	assert_output --partial "is not in the local history"
	"${PY}" "${RENDER}" --write --repo-root "${root}" >/dev/null
	run "${PY}" "${VALIDATE}" --repo-root "${root}" --skip-ancestry
	assert_success
	assert_output --partial "NOTICE: --skip-ancestry"
}

@test "catalog: non-stable entries need a one-line reason; stable entries must not carry one" {
	local root
	root="$(_fixture_root)"
	_edit_catalog "${root}" '
del entries["demo-action"]["reason"]
entries["reusable-demo"]["reason"] = "why"'
	run "${PY}" "${VALIDATE}" --repo-root "${root}"
	assert_failure
	assert_output --partial "demo-action: tier \`preview\` requires a one-line \`reason\`"
	assert_output --partial "reusable-demo: \`reason\` is for non-stable entries"
}

@test "catalog: deprecated needs a replacement that exists; others must not set one" {
	local root
	root="$(_fixture_root)"
	_edit_catalog "${root}" '
entries["demo-action"]["tier"] = "deprecated"
entries["demo-action"]["replacement"] = "nope"
entries["detect-changes"]["replacement"] = "demo-action"'
	run "${PY}" "${VALIDATE}" --repo-root "${root}"
	assert_failure
	assert_output --partial "demo-action: deprecated entries need a \`replacement\`"
	assert_output --partial "detect-changes: \`replacement\` is only valid on deprecated entries"
}

@test "catalog: unknown tier, unknown key and unknown package manager fail" {
	local root
	root="$(_fixture_root)"
	_edit_catalog "${root}" '
entries["demo-action"]["tier"] = "beta"
entries["detect-changes"]["check-names"] = ["x"]
entries["reusable-demo"]["package-managers"] = ["yarn"]'
	run "${PY}" "${VALIDATE}" --repo-root "${root}"
	assert_failure
	assert_output --partial "demo-action: \`kind\` must be one of"
	assert_output --partial "detect-changes: unknown key \`check-names\` for a composite-action"
	assert_output --partial "reusable-demo: unknown package manager \`yarn\`"
}

@test "catalog: renaming a job without updating check-names fails" {
	local root
	root="$(_fixture_root)"
	sed -i.bak 's/default: "Demo Tests"/default: "Demo Suite"/' "${root}/.github/workflows/reusable-demo.yml"
	run "${PY}" "${VALIDATE}" --repo-root "${root}"
	assert_failure
	assert_output --partial "reusable-demo: \`check-names\` must match the workflow's job names ('Demo Suite')"
}

@test "catalog: runners must include the workflow's default runner" {
	local root
	root="$(_fixture_root)"
	_edit_catalog "${root}" 'entries["reusable-demo"]["runners"] = ["macos-15"]'
	run "${PY}" "${VALIDATE}" --repo-root "${root}"
	assert_failure
	assert_output --partial "reusable-demo: \`runners\` must include the default runner(s) ubuntu-24.04"
}

@test "catalog: a stale docs/catalog.md fails both render --check and validate" {
	local root
	root="$(_fixture_root)"
	_edit_catalog "${root}" 'entries["reusable-demo"]["limitations"].append("New limitation")'
	run "${PY}" "${RENDER}" --check --repo-root "${root}"
	assert_failure
	assert_output --partial "ERROR: docs/catalog.md is out of date with catalog/catalog.yml"
	run "${PY}" "${VALIDATE}" --repo-root "${root}"
	assert_failure
	assert_output --partial "docs/catalog.md: out of date with the catalog"
	"${PY}" "${RENDER}" --write --repo-root "${root}" >/dev/null
	run "${PY}" "${RENDER}" --check --repo-root "${root}"
	assert_success
}

@test "catalog: a hand edit inside the README index block is reported as drift" {
	local root
	root="$(_fixture_root)"
	sed -i.bak 's/^Stable entry points/Hand-edited entry points/' "${root}/README.md"
	run "${PY}" "${RENDER}" --check --repo-root "${root}"
	assert_failure
	assert_output --partial "ERROR: README.md is out of date"
}

@test "catalog: render rewrites only the README block between the markers" {
	local root
	root="$(_fixture_root)"
	run cat "${root}/README.md"
	assert_output --partial "Intro stays put."
	assert_output --partial "Outro stays put."
	assert_output --partial "| Reusable workflows (1) | [docs/workflows/](docs/workflows/README.md) | 1 stable · 0 preview · 0 internal · 0 deprecated |"
	assert_output --partial "- Reusable workflows: [\`reusable-demo\`](docs/catalog.md#reusable-demo)"
	assert_output --partial "- Composite actions: —"
}

@test "catalog: render fails when the README markers are missing" {
	local root
	root="$(_fixture_root)"
	printf '# Demo\n' >"${root}/README.md"
	run "${PY}" "${RENDER}" --check --repo-root "${root}"
	assert_failure
	assert_output --partial "catalog-index markers missing"
}

@test "catalog: docs/catalog.md shows evidence for stable and a banner for every other tier" {
	local root
	root="$(_fixture_root)"
	run cat "${root}/docs/catalog.md"
	assert_output --partial "Generated by scripts/ci/catalog/render.py"
	assert_output --partial "[\`demo.yml\`](https://github.com/example/consumer-fixture/actions/runs/123)"
	assert_output --partial "> [!WARNING]
> **Preview.** No external-fixture run yet"
	assert_output --partial "> [!NOTE]
> **Internal.** Used by the demo only"
	assert_output --partial "- **Check names:** \`Demo Tests\`"
	assert_output --partial "Do one demo thing"
	refute_output --partial "Then explain it at length"
}

@test "catalog: deprecated entries render a caution banner linking the replacement" {
	local root
	root="$(_fixture_root)"
	_edit_catalog "${root}" '
entries["detect-changes"]["tier"] = "deprecated"
entries["detect-changes"]["replacement"] = "demo-action"'
	"${PY}" "${RENDER}" --write --repo-root "${root}" >/dev/null
	run cat "${root}/docs/catalog.md"
	assert_output --partial "> [!CAUTION]
> **Deprecated.** Used by the demo only
> Migrate to [\`demo-action\`](#demo-action)."
}
