---
name: 'Setup Rust'
description: 'Setup Rust toolchain with cargo caching'
author: 'lgtm-hq'

inputs:
  toolchain:
    description: 'Rust toolchain (e.g., stable, nightly, 1.75.0)'
    required: false
    default: 'stable'
  components:
    description: 'Components to install (e.g., clippy, rustfmt)'
    required: false
    default: ''
  targets:
    description: 'Additional targets to install (comma-separated)'
    required: false
    default: ''
  cache:
    description: 'Enable cargo cache'
    required: false
    default: 'true'
  cache-dependency-path:
    description: 'Path to Cargo.lock for cache key'
    required: false
    default: '**/Cargo.lock'
  working-directory:
    description: 'Working directory for cargo commands'
    required: false
    default: '.'

outputs:
  rustc-version:
    description: 'Installed rustc version'
    value: ${{ steps.rust-version.outputs.rustc }}
  cargo-version:
    description: 'Installed cargo version'
    value: ${{ steps.rust-version.outputs.cargo }}
  cache-hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      # Pinned to SHA for supply chain security
      uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203 # master
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}

    - name: Get Rust versions
      id: rust-version
      shell: bash
      env:
        STEP: version
      run: ${{ github.action_path }}/../../../scripts/ci/actions/setup-rust.sh

    - name: Configure cargo for CI
      shell: bash
      env:
        STEP: cargo-env
      run: ${{ github.action_path }}/../../../scripts/ci/actions/setup-rust.sh

    - name: Cache cargo registry and build
      if: inputs.cache == 'true'
      id: cache
      # Pinned to SHA for supply chain security
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ${{ inputs.working-directory }}/target/
        # Cache key must be single line - includes toolchain for invalidation
        # Cache key includes toolchain for proper invalidation
        key:
          cargo-${{ runner.os }}-${{ inputs.toolchain }}-${{
          hashFiles(inputs.cache-dependency-path) }}
        restore-keys: |
          cargo-${{ runner.os }}-${{ inputs.toolchain }}-
          cargo-${{ runner.os }}-

    - name: Install cargo-binstall
      shell: bash
      env:
        STEP: binstall
      run: ${{ github.action_path }}/../../../scripts/ci/actions/setup-rust.sh

branding:
  icon: 'cpu'
  color: 'orange'
