name: 'Setup Rust'
description: 'Setup Rust toolchain with cargo caching'
author: 'lgtm-hq'

inputs:
  toolchain:
    description: 'Rust toolchain to install (e.g., "stable", "nightly", "1.75.0")'
    required: false
    default: 'stable'
  components:
    description: 'Additional components to install (comma-separated, e.g., "clippy, rustfmt")'
    required: false
    default: ''
  targets:
    description: 'Additional targets to install (comma-separated)'
    required: false
    default: ''
  cache:
    description: 'Enable cargo cache'
    required: false
    default: 'true'
  cache-dependency-path:
    description: 'Path to Cargo.lock for cache key'
    required: false
    default: '**/Cargo.lock'
  working-directory:
    description: 'Working directory for cargo commands'
    required: false
    default: '.'

outputs:
  rustc-version:
    description: 'Installed rustc version'
    value: ${{ steps.rust-version.outputs.rustc }}
  cargo-version:
    description: 'Installed cargo version'
    value: ${{ steps.rust-version.outputs.cargo }}
  cache-hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203 # master
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}

    - name: Get Rust versions
      id: rust-version
      shell: bash
      run: |
        rustc_version=$(rustc --version | awk '{print $2}')
        cargo_version=$(cargo --version | awk '{print $2}')
        echo "rustc=$rustc_version" >> "$GITHUB_OUTPUT"
        echo "cargo=$cargo_version" >> "$GITHUB_OUTPUT"
        echo "rustc version: $rustc_version"
        echo "cargo version: $cargo_version"

    - name: Configure cargo for CI
      shell: bash
      run: |
        # Use sparse registry protocol for faster downloads
        echo "CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse" >> "$GITHUB_ENV"
        # Incremental compilation is not useful in CI
        echo "CARGO_INCREMENTAL=0" >> "$GITHUB_ENV"
        # More readable backtraces
        echo "RUST_BACKTRACE=short" >> "$GITHUB_ENV"

    - name: Cache cargo registry and build
      if: inputs.cache == 'true'
      id: cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ${{ inputs.working-directory }}/target/
        key: cargo-${{ runner.os }}-${{ inputs.toolchain }}-${{ hashFiles(inputs.cache-dependency-path) }}
        restore-keys: |
          cargo-${{ runner.os }}-${{ inputs.toolchain }}-
          cargo-${{ runner.os }}-

    - name: Install cargo-binstall
      shell: bash
      run: |
        if ! command -v cargo-binstall &> /dev/null; then
          echo "Installing cargo-binstall..."
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
        else
          echo "cargo-binstall already installed"
        fi

branding:
  icon: 'cpu'
  color: 'orange'
