---
name: 'Egress Audit'
description: 'Audit and restrict network egress from workflows'
author: 'lgtm-hq'

inputs:
  mode:
    description: 'Mode: audit (log), report (summary), or block (enforce)'
    required: false
    default: 'audit'
  allowed-domains:
    description: 'Allowed domains when mode is block (newline-separated)'
    required: false
    default: |
      github.com
      api.github.com
      uploads.github.com
      objects.githubusercontent.com
      raw.githubusercontent.com
      codeload.github.com
      pkg.github.com
      ghcr.io
      registry.npmjs.org
      pypi.org
      files.pythonhosted.org
      crates.io
      static.crates.io
      rubygems.org
  report-format:
    description: 'Report format: "summary" (step summary), "json", or "none"'
    required: false
    default: 'summary'
  fail-on-violation:
    description: 'Fail workflow on unauthorized egress (block mode only)'
    required: false
    default: 'false'

outputs:
  violations-detected:
    description: 'Whether any egress policy violations were detected'
    value: ${{ steps.audit.outputs.violations-detected }}
  egress-log:
    description: 'Path to the egress log file'
    value: ${{ steps.audit.outputs.egress-log }}

runs:
  using: 'composite'
  steps:
    - name: Setup egress monitoring
      id: setup
      shell: bash
      env:
        STEP: setup
        MODE: ${{ inputs.mode }}
        ALLOWED_DOMAINS: ${{ inputs['allowed-domains'] }}
      run: ${{ github.action_path }}/../../../scripts/ci/actions/egress-audit.sh

    - name: Configure egress policy
      id: audit
      shell: bash
      env:
        STEP: audit
        MODE: ${{ inputs.mode }}
      run: ${{ github.action_path }}/../../../scripts/ci/actions/egress-audit.sh

    - name: Generate egress report
      if: inputs.report-format != 'none'
      shell: bash
      env:
        STEP: report
        MODE: ${{ inputs.mode }}
        REPORT_FORMAT: ${{ inputs['report-format'] }}
      run: ${{ github.action_path }}/../../../scripts/ci/actions/egress-audit.sh

branding:
  icon: 'wifi'
  color: 'yellow'
