#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate ``docs/catalog.md`` and the README component index from the catalog.

Both outputs are derived from ``catalog/catalog.yml`` (#1079) and never edited
by hand. ``--check`` reports drift without writing, which is how CI and the
BATS suite keep the committed files honest; ``--write`` regenerates them.

The README is only touched between the ``catalog-index`` markers.

Usage:
    render.py --write [--repo-root DIR]
    render.py --check [--repo-root DIR]
"""

# pylint: disable=invalid-name  # CLI script; the path is the contract

from __future__ import annotations

import argparse
import sys
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

# catalog_lib lives next to this script.
sys.path.insert(0, str(Path(__file__).resolve().parent))
import catalog_lib  # noqa: E402  # pylint: disable=wrong-import-position
from catalog_lib import (  # noqa: E402  # pylint: disable=wrong-import-position
    Kind,
    Tier,
)

DOC_RELPATH = Path("docs") / "catalog.md"
README_RELPATH = Path("README.md")
INDEX_BEGIN = (
    "<!-- BEGIN catalog-index: generated by scripts/ci/catalog/render.py "
    "from catalog/catalog.yml; do not edit -->"
)
INDEX_END = "<!-- END catalog-index -->"
GENERATED_NOTE = (
    "<!-- Generated by scripts/ci/catalog/render.py from catalog/catalog.yml; "
    "do not edit. Regenerate with: python3 scripts/ci/catalog/render.py --write -->"
)
REGENERATE_HINT = "Regenerate with: python3 scripts/ci/catalog/render.py --write"

KIND_TITLES = {
    Kind.REUSABLE_WORKFLOW: "Reusable workflows",
    Kind.COMPOSITE_ACTION: "Composite actions",
}
KIND_INDEX = {
    Kind.REUSABLE_WORKFLOW: ("docs/workflows/", "docs/workflows/README.md"),
    Kind.COMPOSITE_ACTION: ("docs/actions/", "docs/actions/README.md"),
}
KIND_HIGHLIGHTS = {
    Kind.REUSABLE_WORKFLOW: ", ".join(
        (
            "Quality lint",
            "per-language tests",
            "Docker",
            "Pages",
            "release automation",
            "security audit",
        ),
    ),
    Kind.COMPOSITE_ACTION: (
        "Setup, security/egress, testing, coverage, publishing, release, PR comments"
    ),
}
LIBRARIES_ROW = (
    "| Shell libraries | [docs/libraries/](docs/libraries/README.md) | — "
    "| Logging, GitHub Actions helpers, installers, release/changelog, "
    "coverage parsing |"
)
TIER_MEANING = {
    Tier.STABLE: (
        "Green from the external consumer fixture at a commit on `main`; the run "
        "is linked. Inputs, outputs, permissions and check names change only with "
        "a documented migration."
    ),
    Tier.PREVIEW: (
        "Shipped and maintained, but not yet proven from outside the org (or only "
        "partly). May change without a migration path."
    ),
    Tier.INTERNAL: (
        "Exists for lgtm-ci's own workflows or lgtm-hq infrastructure. Not "
        "supported for other callers."
    ),
    Tier.DEPRECATED: (
        "Kept as a migration shim with a warning; use the named replacement. "
        "Removal follows the governance process (#1082)."
    ),
}
BANNERS = {
    Tier.PREVIEW: ("WARNING", "Preview"),
    Tier.INTERNAL: ("NOTE", "Internal"),
    Tier.DEPRECATED: ("CAUTION", "Deprecated"),
}
DOC_INTRO = (
    "Every public reusable workflow and composite action, with its support tier,",
    "the evidence behind the tier, the caller permissions it needs, and what it",
    "does not do.",
)
DOC_PERMISSIONS_NOTE = (
    "Permissions are the block the **calling job** must grant. For a reusable",
    "workflow it is the union GitHub validates before any job runs (see",
    "[Caller snippets and permissions](README.md#caller-snippets-and-permissions))",
    "and the validator requires the catalog to equal it. For a composite action it",
    "is maintained by hand; only the scopes the permissions validator derives",
    "(`detect-changes`) are machine-checked.",
    "",
    "Check names are the callee job names, which GitHub shows as",
    "`<caller job> / <name>` with matrix values appended. A job that calls a",
    "nested reusable is listed as `<job> / <nested job>`; when that job is skipped",
    "by its `if:`, GitHub reports a single check named `<caller job> / <job>`.",
    "",
    "Evidence names the lgtm-ci commit the fixture run was pinned to. The",
    "validator requires that commit to be on lgtm-ci's `main` and in the history",
    "of the commit being checked; the fixture branch the run happened on does not",
    "matter. Evidence is a point-in-time claim: when an entry's file changes after",
    "its evidence commit, the validator prints a notice until the run is refreshed.",
)
INDEX_OUTRO = (
    "Everything else is `preview`, `internal` or `deprecated`; tiers, evidence,",
    "permissions and prerequisites for every entry are in",
    "[docs/catalog.md](docs/catalog.md).",
)


@dataclass(frozen=True)
class Output:
    """A generated file and its expected content.

    Attributes:
        path: Repository-relative path.
        content: Full expected file content.
    """

    path: Path
    content: str


def entry_summary(
    repo_root: Path,
    entry: dict[str, Any],
) -> str:
    """Return the one-line description of an entry from its own YAML.

    Args:
        repo_root: Repository root.
        entry: Catalog entry.

    Returns:
        The workflow ``name:`` without its "Reusable" prefix, or the first
        sentence of the action ``description:``.
    """
    kind = Kind(entry["kind"])
    path = repo_root / catalog_lib.entry_path(kind=kind, entry_id=entry["id"])
    text = path.read_text(encoding="utf-8")
    document = catalog_lib.yaml.safe_load(text) or {}
    if kind is Kind.REUSABLE_WORKFLOW:
        name = str(document.get("name", entry["id"]))
        for prefix in ("Reusable:", "Reusable -", "Reusable"):
            if name.startswith(prefix):
                name = name[len(prefix) :]
                break
        return name.strip()
    description = " ".join(str(document.get("description", "")).split())
    sentence = description.split(". ")[0].rstrip(".")
    return sentence or entry["id"]


def code_list(
    values: Iterable[str],
) -> str:
    """Render values as comma-separated inline code, or an em dash.

    Args:
        values: Strings to render.

    Returns:
        Markdown fragment.
    """
    rendered = ", ".join(f"`{value}`" for value in values)
    return rendered or "—"


def permission_list(
    permissions: dict[str, str],
) -> str:
    """Render a permissions mapping as inline code pairs.

    Args:
        permissions: Scope-to-level mapping.

    Returns:
        Markdown fragment.
    """
    pairs = sorted(permissions.items())
    return code_list(f"{scope}: {level}" for scope, level in pairs)


def table_cell(
    text: str,
) -> str:
    """Escape a value for a Markdown table cell.

    Args:
        text: Cell text.

    Returns:
        Text with pipes escaped.
    """
    return text.replace("|", "\\|")


def ordered(
    entries: list[dict[str, Any]],
    kind: Kind,
    tier: Tier,
) -> list[dict[str, Any]]:
    """Select one kind and tier, in catalog order.

    Args:
        entries: All catalog entries.
        kind: Kind to keep.
        tier: Tier to keep.

    Returns:
        Matching entries.
    """
    return [e for e in entries if e["kind"] == kind and e["tier"] == tier]


def banner_lines(
    entry: dict[str, Any],
) -> list[str]:
    """Return the GitHub alert shown above a non-stable entry.

    Args:
        entry: Catalog entry.

    Returns:
        Alert lines followed by a blank line; empty for stable entries.
    """
    tier = Tier(entry["tier"])
    if tier not in BANNERS:
        return []
    alert, label = BANNERS[tier]
    lines = [f"> [!{alert}]", f"> **{label}.** {entry['reason']}"]
    if tier is Tier.DEPRECATED:
        target = entry["replacement"]
        lines.append(f"> Migrate to [`{target}`](#{target}).")
    return lines + [""]


def fact_lines(
    entry: dict[str, Any],
    fixture_repository: str,
) -> list[str]:
    """Return the bulleted facts of one entry.

    Args:
        entry: Catalog entry.
        fixture_repository: ``owner/name`` of the external fixture.

    Returns:
        Bullet lines followed by a blank line.
    """
    kind = Kind(entry["kind"])
    path = catalog_lib.entry_path(kind=kind, entry_id=entry["id"]).as_posix()
    facts = [
        f"- **Path:** [`{path}`](../{path})",
        f"- **Tier:** {entry['tier']}",
    ]
    evidence = entry.get("evidence")
    if evidence:
        commit = evidence["last-green"][:8]
        facts.append(
            f"- **Evidence:** [`{evidence['fixture']}`]({evidence['run']}) in "
            f"`{fixture_repository}`, green at lgtm-ci `{commit}`",
        )
    facts += [
        f"- **Permissions:** {permission_list(entry['permissions'])}",
        f"- **Runners:** {code_list(entry['runners'])}",
        f"- **Package managers:** {code_list(entry['package-managers'])}",
    ]
    if kind is Kind.REUSABLE_WORKFLOW:
        facts.append(f"- **Check names:** {code_list(entry['check-names'])}")
    return facts + [""]


def render_entry(
    repo_root: Path,
    entry: dict[str, Any],
    fixture_repository: str,
) -> list[str]:
    """Render one entry's section of ``docs/catalog.md``.

    Args:
        repo_root: Repository root.
        entry: Catalog entry.
        fixture_repository: ``owner/name`` of the external fixture.

    Returns:
        Markdown lines, ending with a blank line.
    """
    summary = entry_summary(repo_root=repo_root, entry=entry)
    lines = [f"#### `{entry['id']}`", "", summary, ""]
    lines += banner_lines(entry=entry)
    lines += fact_lines(entry=entry, fixture_repository=fixture_repository)
    sections = (
        ("prerequisites", "Prerequisites"),
        ("limitations", "Limitations"),
    )
    for key, title in sections:
        if entry[key]:
            lines += [f"**{title}:**", ""]
            lines += [f"- {item}" for item in entry[key]]
            lines.append("")
    return lines


def summary_table(
    entries: list[dict[str, Any]],
) -> list[str]:
    """Render the per-kind tier count table.

    Args:
        entries: All catalog entries.

    Returns:
        Table lines followed by a blank line.
    """
    header = " | ".join(f"`{tier.value}`" for tier in Tier)
    lines = [
        f"| Kind | {header} | Total |",
        "| ---- |" + " ---- |" * (len(Tier) + 1),
    ]
    for kind in Kind:
        counts = [len(ordered(entries=entries, kind=kind, tier=t)) for t in Tier]
        cells = " | ".join(str(count) for count in counts)
        lines.append(f"| {KIND_TITLES[kind]} | {cells} | {sum(counts)} |")
    return lines + [""]


def kind_section(
    repo_root: Path,
    entries: list[dict[str, Any]],
    kind: Kind,
    fixture_repository: str,
) -> list[str]:
    """Render one kind's index table and entry sections.

    Args:
        repo_root: Repository root.
        entries: All catalog entries.
        kind: Kind to render.
        fixture_repository: ``owner/name`` of the external fixture.

    Returns:
        Markdown lines.
    """
    lines = [
        f"## {KIND_TITLES[kind]}",
        "",
        "| Entry | Tier | Summary |",
        "| ----- | ---- | ------- |",
    ]
    for tier in Tier:
        for entry in ordered(entries=entries, kind=kind, tier=tier):
            summary = table_cell(entry_summary(repo_root=repo_root, entry=entry))
            anchor = f"[`{entry['id']}`](#{entry['id']})"
            lines.append(f"| {anchor} | `{tier.value}` | {summary} |")
    lines.append("")
    for tier in Tier:
        selected = ordered(entries=entries, kind=kind, tier=tier)
        if not selected:
            continue
        lines += [f"### {KIND_TITLES[kind]}: {tier.value}", ""]
        for entry in selected:
            lines += render_entry(
                repo_root=repo_root,
                entry=entry,
                fixture_repository=fixture_repository,
            )
    return lines


def render_doc(
    repo_root: Path,
    catalog: dict[str, Any],
) -> str:
    """Render the full ``docs/catalog.md``.

    Args:
        repo_root: Repository root.
        catalog: Parsed catalog.

    Returns:
        File content.
    """
    entries: list[dict[str, Any]] = catalog["entries"]
    fixture = catalog["fixture-repository"]
    fixture_link = f"[`{fixture}`](https://github.com/{fixture})"
    lines = [
        GENERATED_NOTE,
        "<!-- markdownlint-disable MD013 -- generated tables and long list items -->",
        "",
        "# Support catalog",
        "",
        *DOC_INTRO,
        f"`stable` means a green run from the external fixture {fixture_link},",
        "which calls lgtm-ci from outside the org at an exact commit with no",
        "`tooling-ref`.",
        "",
        "## Tiers",
        "",
        "| Tier | Meaning |",
        "| ---- | ------- |",
        *(f"| `{tier.value}` | {TIER_MEANING[tier]} |" for tier in Tier),
        "",
        *DOC_PERMISSIONS_NOTE,
        "",
        "## Summary",
        "",
        *summary_table(entries=entries),
    ]
    for kind in Kind:
        lines += kind_section(
            repo_root=repo_root,
            entries=entries,
            kind=kind,
            fixture_repository=fixture,
        )
    return "\n".join(lines).rstrip("\n") + "\n"


def render_index(
    catalog: dict[str, Any],
) -> str:
    """Render the README component index block, markers included.

    Args:
        catalog: Parsed catalog.

    Returns:
        The block text without a trailing newline.
    """
    entries: list[dict[str, Any]] = catalog["entries"]
    lines = [
        INDEX_BEGIN,
        "<!-- markdownlint-disable MD013 -- component index table -->",
        "",
        "| Area | Index | Support tiers | Highlights |",
        "| ---- | ----- | ------------- | ---------- |",
    ]
    for kind in Kind:
        tallies = []
        for tier in Tier:
            selected = ordered(entries=entries, kind=kind, tier=tier)
            tallies.append(f"{len(selected)} {tier.value}")
        counts = " · ".join(tallies)
        total = sum(1 for e in entries if e["kind"] == kind)
        label, link = KIND_INDEX[kind]
        area = f"{KIND_TITLES[kind]} ({total})"
        lines.append(
            f"| {area} | [{label}]({link}) | {counts} | {KIND_HIGHLIGHTS[kind]} |",
        )
    lines += [
        LIBRARIES_ROW,
        "",
        "Stable entry points, each green from the external consumer fixture:",
        "",
    ]
    for kind in Kind:
        stable = ordered(entries=entries, kind=kind, tier=Tier.STABLE)
        links = ", ".join(f"[`{e['id']}`](docs/catalog.md#{e['id']})" for e in stable)
        lines.append(f"- {KIND_TITLES[kind]}: {links or '—'}")
    lines += [
        "",
        "<!-- markdownlint-enable MD013 -->",
        "",
        *INDEX_OUTRO,
        INDEX_END,
    ]
    return "\n".join(lines)


def replace_index(
    readme: str,
    block: str,
) -> str:
    """Swap the marked block in the README text.

    Args:
        readme: Current README content.
        block: New block, markers included.

    Returns:
        README content with the block replaced.

    Raises:
        ValueError: When the markers are missing or out of order.
    """
    start = readme.find(INDEX_BEGIN)
    end = readme.find(INDEX_END)
    if start < 0 or end < start:
        message = "catalog-index markers missing or out of order"
        raise ValueError(f"{README_RELPATH}: {message}")
    if readme.count(INDEX_BEGIN) > 1 or readme.count(INDEX_END) > 1:
        message = "catalog-index markers appear more than once"
        raise ValueError(f"{README_RELPATH}: {message}")
    return readme[:start] + block + readme[end + len(INDEX_END) :]


def expected_outputs(
    repo_root: Path,
) -> list[Output]:
    """Compute every generated file's expected content.

    Args:
        repo_root: Repository root.

    Returns:
        Outputs in a stable order.

    Raises:
        ValueError: When the catalog or the README markers are malformed.
    """
    catalog_path = repo_root / catalog_lib.CATALOG_RELPATH
    catalog = catalog_lib.load_catalog(path=catalog_path)
    readme = (repo_root / README_RELPATH).read_text(encoding="utf-8")
    doc = render_doc(repo_root=repo_root, catalog=catalog)
    index = replace_index(readme=readme, block=render_index(catalog=catalog))
    return [
        Output(path=DOC_RELPATH, content=doc),
        Output(path=README_RELPATH, content=index),
    ]


def stale_outputs(
    repo_root: Path,
) -> list[Path]:
    """List generated files whose committed content differs from the catalog.

    Args:
        repo_root: Repository root.

    Returns:
        Repository-relative paths that need regenerating.
    """
    stale = []
    for output in expected_outputs(repo_root=repo_root):
        target = repo_root / output.path
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        if current != output.content:
            stale.append(output.path)
    return stale


def parse_args(
    argv: list[str],
) -> argparse.Namespace:
    """Parse CLI arguments.

    Args:
        argv: Argument vector without the program name.

    Returns:
        Parsed arguments.
    """
    parser = argparse.ArgumentParser(
        description="Render docs/catalog.md and the README index.",
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--write",
        action="store_true",
        help="Regenerate the files",
    )
    mode.add_argument(
        "--check",
        action="store_true",
        help="Fail if a file is out of date",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=catalog_lib.REPO_ROOT,
        help="Repository root (default: this checkout)",
    )
    return parser.parse_args(argv)


def run_check(
    repo_root: Path,
) -> int:
    """Report generated files that are out of date.

    Args:
        repo_root: Repository root.

    Returns:
        Process exit code.
    """
    stale = stale_outputs(repo_root=repo_root)
    for path in stale:
        source = catalog_lib.CATALOG_RELPATH
        print(f"ERROR: {path} is out of date with {source}", file=sys.stderr)
    if stale:
        print(REGENERATE_HINT, file=sys.stderr)
        return 1
    print("OK: generated catalog docs are current")
    return 0


def main(
    argv: list[str],
) -> int:
    """Run the renderer.

    Args:
        argv: Argument vector without the program name.

    Returns:
        Process exit code.
    """
    args = parse_args(argv=argv)
    repo_root: Path = args.repo_root.resolve()
    try:
        if args.check:
            return run_check(repo_root=repo_root)
        for output in expected_outputs(repo_root=repo_root):
            (repo_root / output.path).write_text(output.content, encoding="utf-8")
            print(f"wrote {output.path}")
    except (OSError, ValueError, KeyError, catalog_lib.yaml.YAMLError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(argv=sys.argv[1:]))
