#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Purpose: Generate the read-only variant of each facade reusable (or check it) (#1081)
#
# Usage:
#   bash scripts/ci/workflows/sync-readonly-variants.sh           # rewrite in place
#   bash scripts/ci/workflows/sync-readonly-variants.sh --check   # exit 1 on drift
#
# GitHub validates the permission union of a reusable workflow before any job
# `if:` runs, so a caller of a facade that can publish must grant the publish
# scopes even when it never publishes. A facade opts into a read-only variant
# with one marker line, conventionally inside the omit region that holds the
# facade's own header comment so the variant does not inherit it:
#
#   # lgtm-ci-readonly:omit:begin
#   # lgtm-ci-readonly-variant: reusable-test-node-run.yml
#   # lgtm-ci-readonly:omit:end
#
# and wraps each mutation-only region (the publish job, inputs and env lines
# only that job needs) in the same begin/end pair. A variant that still
# carried the marker would be rejected rather than treated as a facade.
#
# The variant is the facade with the lines before `---` replaced by the
# generated header below, the omitted regions dropped and ` (read-only)`
# appended to the first top-level `name:` (plain or double-quoted scalar
# without a trailing comment; anything else is an error). Everything else, job ids and job names
# included, is copied verbatim, so the variant reports the same check names
# under the caller's job id and cannot drift from the facade's behaviour. The
# facade itself is never rewritten and keeps calling its jobs inline: nesting
# them under a facade job would add a segment to every check name that org
# rulesets require. The BATS contract test runs `--check`; after editing a
# facade, run this script and commit the variant with it.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "$SCRIPT_DIR/../../.." && pwd)}"
WORKFLOWS_DIR="${WORKFLOWS_DIR:-$REPO_ROOT/.github/workflows}"

VARIANT_MARK="# lgtm-ci-readonly-variant:"
OMIT_BEGIN="# lgtm-ci-readonly:omit:begin"
OMIT_END="# lgtm-ci-readonly:omit:end"
GENERATED_MARK="# GENERATED by scripts/ci/workflows/sync-readonly-variants.sh"

check=0
case "${1:-}" in
"") ;;
--check) check=1 ;;
*)
	echo "usage: $0 [--check]" >&2
	exit 2
	;;
esac

# Print the variant for one facade on stdout; exit 1 on unbalanced markers.
render_variant() {
	local facade="$1"
	local facade_name
	facade_name="$(basename "$facade")"
	cat <<EOF
$GENERATED_MARK from
# $facade_name — do not edit. Edit the facade, then re-run the script.
#
# Read-only variant (#1081): the facade's jobs without its mutation jobs, so
# the permission union a caller must grant holds no write scope. Job ids and
# names match the facade, so check names under the caller's job id do too.
# Results stay in this call's artifacts (results.v1, #1080); see
# docs/reusable-workflows.md "Read-only variants" to publish them separately.
EOF
	awk -v omit_begin="$OMIT_BEGIN" -v omit_end="$OMIT_END" -v facade="$facade_name" '
		!started { if ($0 == "---") { started = 1; print } ; next }
		index($0, omit_begin) {
			if (omitting) { printf "%s:%d: nested %s\n", facade, NR, omit_begin > "/dev/stderr"; bad = 1 }
			omitting = 1; next
		}
		index($0, omit_end) {
			if (!omitting) { printf "%s:%d: %s without begin\n", facade, NR, omit_end > "/dev/stderr"; bad = 1 }
			omitting = 0; next
		}
		omitting { next }
		/^name: / && !renamed {
			renamed = 1
			if ($0 ~ /^name: [^"\047#|>][^#]*[^ #]$/) { print $0 " (read-only)"; next }
			if ($0 ~ /^name: "[^"#]*"$/) { sub(/"$/, " (read-only)\""); print; next }
			printf "%s:%d: cannot rename this name: form; use a plain or double-quoted scalar\n", facade, NR > "/dev/stderr"
			bad = 1; next
		}
		{ print }
		END {
			if (!started) { printf "%s: no --- document start\n", facade > "/dev/stderr"; bad = 1 }
			if (omitting) { printf "%s: unterminated %s\n", facade, omit_begin > "/dev/stderr"; bad = 1 }
			if (!renamed) { printf "%s: no top-level name:\n", facade > "/dev/stderr"; bad = 1 }
			exit bad
		}
	' "$facade"
}

status=0
drifted=()
expected=()
for facade in "$WORKFLOWS_DIR"/reusable-*.yml; do
	if grep -qF "$GENERATED_MARK" "$facade"; then
		# A generated file is never a facade; one still carrying the marker
		# means the facade left it outside every omit region.
		if grep -q "^${VARIANT_MARK}" "$facade"; then
			echo "$(basename "$facade"): generated variant carries ${VARIANT_MARK}; wrap it in an omit region" >&2
			status=1
		fi
		continue
	fi
	variant_name="$(sed -n "s/^${VARIANT_MARK} *//p" "$facade" | head -n 1)"
	[[ -n "$variant_name" ]] || continue
	if [[ ! "$variant_name" =~ ^reusable-[A-Za-z0-9._-]+\.yml$ ]]; then
		echo "$(basename "$facade"): invalid variant name '$variant_name'" >&2
		status=1
		continue
	fi
	expected+=("$variant_name")
	variant="$WORKFLOWS_DIR/$variant_name"

	updated="$(mktemp)"
	if ! render_variant "$facade" >"$updated"; then
		rm -f "$updated"
		status=1
		continue
	fi
	if [[ -f "$variant" ]] && cmp -s "$variant" "$updated"; then
		rm -f "$updated"
		continue
	fi
	if ((check)); then
		drifted+=("$variant_name")
		rm -f "$updated"
	else
		mv "$updated" "$variant"
		echo "wrote $variant_name"
	fi
done

# A generated variant whose facade lost its marker is an orphan: it would
# keep serving a stale copy of the facade.
orphans=()
for workflow in "$WORKFLOWS_DIR"/*.yml; do
	grep -qF "$GENERATED_MARK" "$workflow" || continue
	name="$(basename "$workflow")"
	found=0
	for want in "${expected[@]+"${expected[@]}"}"; do
		[[ "$want" == "$name" ]] && found=1
	done
	((found)) || orphans+=("$name")
done

if ((${#drifted[@]})); then
	printf 'read-only variant out of date: %s\n' "${drifted[@]}" >&2
	echo "run: bash scripts/ci/workflows/sync-readonly-variants.sh" >&2
	status=1
fi
if ((${#orphans[@]})); then
	printf 'generated variant without a facade marker: %s\n' "${orphans[@]}" >&2
	status=1
fi
exit "$status"
