---
name: 'Attest Build'
description: 'Create build attestations using GitHub attestations'
author: 'lgtm-hq'

inputs:
  subject-path:
    description: 'Path to the artifact to attest'
    required: true
  subject-digest:
    description: 'Digest of the artifact (sha256:...)'
    required: false
    default: ''
  subject-name:
    description: 'Name of the artifact'
    required: false
    default: ''
  push-to-registry:
    description: 'Push attestation to container registry'
    required: false
    default: 'false'

outputs:
  attestation-id:
    description: 'ID of the created attestation'
    value: ${{ steps.attest.outputs.attestation-id }}
  attestation-url:
    description: 'URL of the attestation'
    value: ${{ steps.attest.outputs.attestation-url }}
  bundle-path:
    description: 'Path to the attestation bundle'
    value: ${{ steps.attest.outputs.bundle-path }}

runs:
  using: 'composite'
  steps:
    - name: Prepare attestation
      id: prepare
      shell: bash
      env:
        STEP: prepare
        SUBJECT_PATH: ${{ inputs.subject-path }}
        SUBJECT_NAME: ${{ inputs.subject-name }}
        SUBJECT_DIGEST: ${{ inputs.subject-digest }}
      run: ${{ github.action_path }}/../../../scripts/ci/actions/attest-build.sh

    - name: Create attestation
      id: attest
      # Pinned to SHA for supply chain security
      uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 # v2.2.3
      with:
        subject-path: ${{ steps.prepare.outputs.subject-path }}
        subject-digest: ${{ steps.prepare.outputs.subject-digest }}
        subject-name: ${{ steps.prepare.outputs.subject-name }}
        push-to-registry: ${{ inputs.push-to-registry }}

    - name: Generate summary
      shell: bash
      env:
        STEP: summary
        ATTESTATION_ID: ${{ steps.attest.outputs.attestation-id }}
        ATTESTATION_URL: ${{ steps.attest.outputs.attestation-url }}
        BUNDLE_PATH: ${{ steps.attest.outputs.bundle-path }}
        SUBJECT_NAME: ${{ steps.prepare.outputs.subject-name }}
      run: ${{ github.action_path }}/../../../scripts/ci/actions/attest-build.sh

branding:
  icon: 'check-circle'
  color: 'green'
