name: 'Generate Coverage Comment'
description: 'Generate a formatted PR comment from code coverage results'
author: 'lgtm-hq'

inputs:
  coverage-file:
    description: 'Path to coverage summary JSON file'
    required: false
    default: 'coverage/coverage-summary.json'
  format:
    description: 'Coverage file format: "istanbul" (JS), "coverage-py" (Python), "lcov", or "auto"'
    required: false
    default: 'auto'
  report-url:
    description: 'URL to full coverage report (e.g., GitHub Pages URL)'
    required: false
    default: ''
  threshold-lines:
    description: 'Minimum line coverage percentage'
    required: false
    default: '80'
  threshold-branches:
    description: 'Minimum branch coverage percentage'
    required: false
    default: '70'
  threshold-functions:
    description: 'Minimum function coverage percentage'
    required: false
    default: '80'
  show-file-coverage:
    description: 'Show per-file coverage breakdown'
    required: false
    default: 'false'
  max-files:
    description: 'Maximum number of files to show in breakdown'
    required: false
    default: '10'

outputs:
  comment-body:
    description: 'Generated comment body in Markdown'
    value: ${{ steps.generate.outputs.body }}
  lines-coverage:
    description: 'Line coverage percentage'
    value: ${{ steps.generate.outputs.lines }}
  branches-coverage:
    description: 'Branch coverage percentage'
    value: ${{ steps.generate.outputs.branches }}
  functions-coverage:
    description: 'Function coverage percentage'
    value: ${{ steps.generate.outputs.functions }}
  statements-coverage:
    description: 'Statement coverage percentage'
    value: ${{ steps.generate.outputs.statements }}
  passed:
    description: 'Whether coverage meets all thresholds'
    value: ${{ steps.generate.outputs.passed }}

runs:
  using: 'composite'
  steps:
    - name: Generate comment
      id: generate
      shell: bash
      run: |
        COVERAGE_FILE="${{ inputs['coverage-file'] }}"
        FORMAT="${{ inputs.format }}"
        REPORT_URL="${{ inputs['report-url'] }}"
        THRESHOLD_LINES="${{ inputs['threshold-lines'] }}"
        THRESHOLD_BRANCHES="${{ inputs['threshold-branches'] }}"
        THRESHOLD_FUNCTIONS="${{ inputs['threshold-functions'] }}"

        # Check if coverage file exists
        if [[ ! -f "$COVERAGE_FILE" ]]; then
          echo "::warning::Coverage file not found at $COVERAGE_FILE"
          EOF_MARKER="EOF_$(date +%s)"
          echo "body<<$EOF_MARKER" >> "$GITHUB_OUTPUT"
          echo "## Coverage Report" >> "$GITHUB_OUTPUT"
          echo "" >> "$GITHUB_OUTPUT"
          echo "⚠️ No coverage data found" >> "$GITHUB_OUTPUT"
          echo "$EOF_MARKER" >> "$GITHUB_OUTPUT"
          echo "lines=0" >> "$GITHUB_OUTPUT"
          echo "branches=0" >> "$GITHUB_OUTPUT"
          echo "functions=0" >> "$GITHUB_OUTPUT"
          echo "statements=0" >> "$GITHUB_OUTPUT"
          echo "passed=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Auto-detect format
        if [[ "$FORMAT" == "auto" ]]; then
          if jq -e '.total' "$COVERAGE_FILE" > /dev/null 2>&1; then
            FORMAT="istanbul"
          elif jq -e '.totals' "$COVERAGE_FILE" > /dev/null 2>&1; then
            FORMAT="coverage-py"
          else
            FORMAT="istanbul"
          fi
        fi

        # Extract coverage based on format
        case "$FORMAT" in
          istanbul)
            LINES=$(jq -r '.total.lines.pct // 0' "$COVERAGE_FILE")
            BRANCHES=$(jq -r '.total.branches.pct // 0' "$COVERAGE_FILE")
            FUNCTIONS=$(jq -r '.total.functions.pct // 0' "$COVERAGE_FILE")
            STATEMENTS=$(jq -r '.total.statements.pct // 0' "$COVERAGE_FILE")
            ;;
          coverage-py)
            LINES=$(jq -r '.totals.percent_covered // 0' "$COVERAGE_FILE")
            BRANCHES=$(jq -r '.totals.percent_covered_branches // .totals.percent_covered // 0' "$COVERAGE_FILE")
            FUNCTIONS=$LINES  # Python coverage doesn't track functions separately
            STATEMENTS=$LINES
            ;;
          *)
            echo "::error::Unknown coverage format: $FORMAT"
            exit 1
            ;;
        esac

        # Round to integers
        LINES=$(printf "%.0f" "$LINES")
        BRANCHES=$(printf "%.0f" "$BRANCHES")
        FUNCTIONS=$(printf "%.0f" "$FUNCTIONS")
        STATEMENTS=$(printf "%.0f" "$STATEMENTS")

        echo "lines=$LINES" >> "$GITHUB_OUTPUT"
        echo "branches=$BRANCHES" >> "$GITHUB_OUTPUT"
        echo "functions=$FUNCTIONS" >> "$GITHUB_OUTPUT"
        echo "statements=$STATEMENTS" >> "$GITHUB_OUTPUT"

        # Check thresholds
        PASSED=true
        [[ $LINES -lt $THRESHOLD_LINES ]] && PASSED=false
        [[ $BRANCHES -lt $THRESHOLD_BRANCHES ]] && PASSED=false
        [[ $FUNCTIONS -lt $THRESHOLD_FUNCTIONS ]] && PASSED=false
        echo "passed=$PASSED" >> "$GITHUB_OUTPUT"

        # Helper function for score emoji
        score_emoji() {
          local score=$1
          local threshold=$2
          if [[ $score -ge 90 ]]; then
            echo "🟢"
          elif [[ $score -ge $threshold ]]; then
            echo "🟡"
          else
            echo "🔴"
          fi
        }

        # Generate comment body
        BODY="## Coverage Report

        | Metric | Coverage | Threshold |
        |--------|----------|-----------|
        | $(score_emoji $LINES $THRESHOLD_LINES) Lines | **${LINES}%** | ${THRESHOLD_LINES}% |
        | $(score_emoji $BRANCHES $THRESHOLD_BRANCHES) Branches | **${BRANCHES}%** | ${THRESHOLD_BRANCHES}% |
        | $(score_emoji $FUNCTIONS $THRESHOLD_FUNCTIONS) Functions | **${FUNCTIONS}%** | ${THRESHOLD_FUNCTIONS}% |
        | Statements | **${STATEMENTS}%** | - |"

        if [[ -n "$REPORT_URL" ]]; then
          BODY="${BODY}

        [View Full Report](${REPORT_URL})"
        fi

        if [[ "$PASSED" == "true" ]]; then
          BODY="${BODY}

        ✅ Coverage meets all thresholds"
        else
          BODY="${BODY}

        ⚠️ Coverage is below some thresholds"
        fi

        # Output body (handle multiline)
        EOF_MARKER="EOF_$(date +%s)"
        echo "body<<$EOF_MARKER" >> "$GITHUB_OUTPUT"
        echo "$BODY" >> "$GITHUB_OUTPUT"
        echo "$EOF_MARKER" >> "$GITHUB_OUTPUT"

branding:
  icon: 'percent'
  color: 'purple'
