#!/usr/bin/env bats
# SPDX-License-Identifier: MIT
# Purpose: Tests for scripts/ci/actions/generate-coverage-comment.sh

load "../../../helpers/common"

setup() {
	setup_temp_dir
	export GITHUB_OUTPUT="${BATS_TEST_TMPDIR}/github-output"
	touch "$GITHUB_OUTPUT"
}

teardown() {
	teardown_temp_dir
}

write_lcov_fixture() {
	local file="$1"
	cat >"$file" <<'EOF'
TN:
SF:/workspace/src/lib.rs
FN:1,covered_fn
FN:10,missed_fn
FNDA:3,covered_fn
FNDA:0,missed_fn
FNF:2
FNH:1
DA:1,1
DA:2,1
DA:3,1
DA:4,0
LF:4
LH:3
BRDA:2,0,0,1
BRDA:2,0,1,0
BRF:2
BRH:1
end_of_record
EOF
}

@test "generate-coverage-comment: parses explicit lcov metrics and body" {
	local coverage_file="${BATS_TEST_TMPDIR}/rust-coverage.lcov"
	write_lcov_fixture "$coverage_file"

	run env \
		GITHUB_OUTPUT="$GITHUB_OUTPUT" \
		COVERAGE_FILE="$coverage_file" \
		FORMAT="lcov" \
		REPORT_URL="https://example.com/coverage/" \
		THRESHOLD_LINES="70" \
		THRESHOLD_BRANCHES="40" \
		THRESHOLD_FUNCTIONS="40" \
		GITHUB_SERVER_URL="https://github.com" \
		GITHUB_REPOSITORY="lgtm-hq/lgtm-ci" \
		GITHUB_RUN_ID="12345" \
		GITHUB_SHA="abc123" \
		bash "${PROJECT_ROOT}/scripts/ci/actions/generate-coverage-comment.sh"

	assert_success
	assert_file_contains "$GITHUB_OUTPUT" "lines=75"
	assert_file_contains "$GITHUB_OUTPUT" "branches=50"
	assert_file_contains "$GITHUB_OUTPUT" "functions=50"
	assert_file_contains "$GITHUB_OUTPUT" "statements=75"
	assert_file_contains "$GITHUB_OUTPUT" "passed=true"
	assert_file_contains "$GITHUB_OUTPUT" "Code Coverage Report"
	assert_file_contains "$GITHUB_OUTPUT" "unified code coverage workflow"
	assert_file_contains "$GITHUB_OUTPUT" "Status: ✅ PASSED"
	assert_file_contains "$GITHUB_OUTPUT" "Coverage:.*75%"
	assert_file_contains "$GITHUB_OUTPUT" "Lines.*75%"
	assert_file_contains "$GITHUB_OUTPUT" "Branches.*50%"
	assert_file_contains "$GITHUB_OUTPUT" "Functions.*50%"
	assert_file_contains "$GITHUB_OUTPUT" "Statements.*75%"
	assert_file_contains "$GITHUB_OUTPUT" "HTML Coverage Report"
	assert_file_contains "$GITHUB_OUTPUT" "https://example.com/coverage/"
	assert_file_contains "$GITHUB_OUTPUT" "View full build details"
	assert_file_contains "$GITHUB_OUTPUT" "Generated by lgtm-ci coverage workflow"
}

@test "generate-coverage-comment: auto-detects lcov files" {
	local coverage_file="${BATS_TEST_TMPDIR}/lcov.info"
	write_lcov_fixture "$coverage_file"

	run env \
		GITHUB_OUTPUT="$GITHUB_OUTPUT" \
		COVERAGE_FILE="$coverage_file" \
		FORMAT="auto" \
		THRESHOLD_LINES="70" \
		THRESHOLD_BRANCHES="40" \
		THRESHOLD_FUNCTIONS="40" \
		bash "${PROJECT_ROOT}/scripts/ci/actions/generate-coverage-comment.sh"

	assert_success
	assert_file_contains "$GITHUB_OUTPUT" "lines=75"
	assert_file_contains "$GITHUB_OUTPUT" "branches=50"
	assert_file_contains "$GITHUB_OUTPUT" "functions=50"
	assert_file_contains "$GITHUB_OUTPUT" "passed=true"
}

@test "generate-coverage-comment: emits explicit zero lcov metrics in outputs and body" {
	local coverage_file="${BATS_TEST_TMPDIR}/zero.lcov"
	cat >"$coverage_file" <<'EOF'
TN:
SF:/workspace/src/lib.rs
FN:1,missed_fn
FNDA:0,missed_fn
FNF:1
FNH:0
DA:1,0
DA:2,0
LF:2
LH:0
BRDA:1,0,0,0
BRF:1
BRH:0
end_of_record
EOF

	run env \
		GITHUB_OUTPUT="$GITHUB_OUTPUT" \
		COVERAGE_FILE="$coverage_file" \
		FORMAT="lcov" \
		THRESHOLD_LINES="0" \
		THRESHOLD_BRANCHES="0" \
		THRESHOLD_FUNCTIONS="0" \
		bash "${PROJECT_ROOT}/scripts/ci/actions/generate-coverage-comment.sh"

	assert_success
	assert_file_contains "$GITHUB_OUTPUT" "lines=0"
	assert_file_contains "$GITHUB_OUTPUT" "branches=0"
	assert_file_contains "$GITHUB_OUTPUT" "functions=0"
	assert_file_contains "$GITHUB_OUTPUT" "statements=0"
	assert_file_contains "$GITHUB_OUTPUT" "passed=true"
	assert_file_contains "$GITHUB_OUTPUT" "Coverage:.*0%"
	assert_file_contains "$GITHUB_OUTPUT" "Lines.*0%"
	assert_file_contains "$GITHUB_OUTPUT" "Branches.*0%"
	assert_file_contains "$GITHUB_OUTPUT" "Functions.*0%"
	assert_file_contains "$GITHUB_OUTPUT" "Statements.*0%"
}

@test "generate-coverage-comment: fails lcov thresholds when metrics are below minimums" {
	local coverage_file="${BATS_TEST_TMPDIR}/rust-coverage.lcov"
	write_lcov_fixture "$coverage_file"

	run env \
		GITHUB_OUTPUT="$GITHUB_OUTPUT" \
		COVERAGE_FILE="$coverage_file" \
		FORMAT="lcov" \
		THRESHOLD_LINES="80" \
		THRESHOLD_BRANCHES="60" \
		THRESHOLD_FUNCTIONS="60" \
		bash "${PROJECT_ROOT}/scripts/ci/actions/generate-coverage-comment.sh"

	assert_success
	assert_file_contains "$GITHUB_OUTPUT" "passed=false"
	assert_file_contains "$GITHUB_OUTPUT" "Status: ⚠️ BELOW TARGET"
	assert_file_contains "$GITHUB_OUTPUT" "Coverage is below one or more thresholds"
}

@test "generate-coverage-comment: preserves istanbul coverage extraction" {
	local coverage_file="${BATS_TEST_TMPDIR}/coverage-summary.json"
	cat >"$coverage_file" <<'EOF'
{
  "total": {
    "lines": {"pct": 91},
    "branches": {"pct": 82},
    "functions": {"pct": 93},
    "statements": {"pct": 94}
  }
}
EOF

	run env \
		GITHUB_OUTPUT="$GITHUB_OUTPUT" \
		COVERAGE_FILE="$coverage_file" \
		FORMAT="istanbul" \
		THRESHOLD_LINES="80" \
		THRESHOLD_BRANCHES="70" \
		THRESHOLD_FUNCTIONS="80" \
		bash "${PROJECT_ROOT}/scripts/ci/actions/generate-coverage-comment.sh"

	assert_success
	assert_file_contains "$GITHUB_OUTPUT" "lines=91"
	assert_file_contains "$GITHUB_OUTPUT" "branches=82"
	assert_file_contains "$GITHUB_OUTPUT" "functions=93"
	assert_file_contains "$GITHUB_OUTPUT" "statements=94"
	assert_file_contains "$GITHUB_OUTPUT" "passed=true"
	assert_file_contains "$GITHUB_OUTPUT" "Code Coverage Report"
}

@test "generate-coverage-comment: appends test-suite-name to heading when provided" {
	local coverage_file="${BATS_TEST_TMPDIR}/coverage-summary.json"
	cat >"$coverage_file" <<'EOF'
{
  "total": {
    "lines": {"pct": 91},
    "branches": {"pct": 82},
    "functions": {"pct": 93},
    "statements": {"pct": 94}
  }
}
EOF

	run env \
		GITHUB_OUTPUT="$GITHUB_OUTPUT" \
		COVERAGE_FILE="$coverage_file" \
		FORMAT="istanbul" \
		TEST_SUITE_NAME="🦀 Rust Coverage" \
		THRESHOLD_LINES="80" \
		THRESHOLD_BRANCHES="70" \
		THRESHOLD_FUNCTIONS="80" \
		bash "${PROJECT_ROOT}/scripts/ci/actions/generate-coverage-comment.sh"

	assert_success
	assert_file_contains "$GITHUB_OUTPUT" "Code Coverage Report — 🦀 Rust Coverage"
}

@test "generate-coverage-comment: preserves coverage-py coverage extraction" {
	local coverage_file="${BATS_TEST_TMPDIR}/coverage.json"
	cat >"$coverage_file" <<'EOF'
{
  "totals": {
    "percent_covered": 88.4,
    "percent_covered_branches": 77.2
  }
}
EOF

	run env \
		GITHUB_OUTPUT="$GITHUB_OUTPUT" \
		COVERAGE_FILE="$coverage_file" \
		FORMAT="coverage-py" \
		THRESHOLD_LINES="80" \
		THRESHOLD_BRANCHES="70" \
		THRESHOLD_FUNCTIONS="80" \
		bash "${PROJECT_ROOT}/scripts/ci/actions/generate-coverage-comment.sh"

	assert_success
	assert_file_contains "$GITHUB_OUTPUT" "lines=88"
	assert_file_contains "$GITHUB_OUTPUT" "branches=77"
	assert_file_contains "$GITHUB_OUTPUT" "functions=88"
	assert_file_contains "$GITHUB_OUTPUT" "statements=88"
	assert_file_contains "$GITHUB_OUTPUT" "passed=true"
	assert_file_contains "$GITHUB_OUTPUT" "Code Coverage Report"
}
