#!/usr/bin/env bats
# SPDX-License-Identifier: MIT
# Purpose: Tests for scripts/ci/actions/generate-playwright-comment.sh

load "../../../helpers/common"

setup() {
	setup_temp_dir
	export GITHUB_OUTPUT="${BATS_TEST_TMPDIR}/github-output"
	touch "$GITHUB_OUTPUT"
}

teardown() {
	teardown_temp_dir
}

@test "generate-playwright-comment: uses unified report style and failed details" {
	local results_file="${BATS_TEST_TMPDIR}/results.json"
	cat >"$results_file" <<'EOF'
{
  "stats": {
    "expected": 2,
    "unexpected": 1,
    "flaky": 1,
    "skipped": 1,
    "duration": 12345
  },
  "suites": [
    {
      "tests": [
        {"title": "checkout fails gracefully", "status": "failed"}
      ]
    }
  ]
}
EOF

	run env \
		GITHUB_OUTPUT="$GITHUB_OUTPUT" \
		RESULTS_PATH="$results_file" \
		REPORT_URL="https://example.com/playwright/" \
		SHOW_FAILED="true" \
		MAX_FAILED="5" \
		GITHUB_SERVER_URL="https://github.com" \
		GITHUB_REPOSITORY="lgtm-hq/lgtm-ci" \
		GITHUB_RUN_ID="12345" \
		GITHUB_SHA="abc123" \
		bash "${PROJECT_ROOT}/scripts/ci/actions/generate-playwright-comment.sh"

	assert_success
	assert_file_contains "$GITHUB_OUTPUT" "total=5"
	assert_file_contains "$GITHUB_OUTPUT" "passed=2"
	assert_file_contains "$GITHUB_OUTPUT" "failed=1"
	assert_file_contains "$GITHUB_OUTPUT" "skipped=1"
	assert_file_contains "$GITHUB_OUTPUT" "success=false"
	assert_file_contains "$GITHUB_OUTPUT" "Playwright E2E Test Report"
	assert_file_contains "$GITHUB_OUTPUT" "Playwright E2E test workflow"
	assert_file_contains "$GITHUB_OUTPUT" "Status: ❌ FAILED"
	assert_file_contains "$GITHUB_OUTPUT" "Test Results"
	assert_file_contains "$GITHUB_OUTPUT" "checkout fails gracefully"
	assert_file_contains "$GITHUB_OUTPUT" "View Playwright HTML Report"
	assert_file_contains "$GITHUB_OUTPUT" "View full build details"
	assert_file_contains "$GITHUB_OUTPUT" "Generated by lgtm-ci Playwright E2E workflow"
}

@test "generate-playwright-comment: emits styled missing-results body" {
	run env \
		GITHUB_OUTPUT="$GITHUB_OUTPUT" \
		RESULTS_PATH="${BATS_TEST_TMPDIR}/missing.json" \
		bash "${PROJECT_ROOT}/scripts/ci/actions/generate-playwright-comment.sh"

	assert_success
	assert_file_contains "$GITHUB_OUTPUT" "total=0"
	assert_file_contains "$GITHUB_OUTPUT" "passed=0"
	assert_file_contains "$GITHUB_OUTPUT" "failed=0"
	assert_file_contains "$GITHUB_OUTPUT" "skipped=0"
	assert_file_contains "$GITHUB_OUTPUT" "success=false"
	assert_file_contains "$GITHUB_OUTPUT" "Playwright E2E Test Report"
	assert_file_contains "$GITHUB_OUTPUT" "Status: ⚠️ MISSING"
	assert_file_contains "$GITHUB_OUTPUT" "No Playwright results found"
}
