#!/usr/bin/env bats
# SPDX-License-Identifier: MIT
# Purpose: Tests for scripts/ci/actions/generate-shell-test-comment.sh

load "../../../helpers/common"

setup() {
	setup_temp_dir
}

teardown() {
	teardown_temp_dir
}

@test "generate-shell-test-comment: uses unified report style with build metadata" {
	run env \
		TESTS_PASSED="10" \
		TESTS_FAILED="0" \
		TESTS_TOTAL="10" \
		TESTS_SKIPPED="0" \
		COVERAGE_PERCENT="91" \
		COVERAGE_THRESHOLD="80" \
		JOB_RESULT="success" \
		GITHUB_SERVER_URL="https://github.com" \
		GITHUB_REPOSITORY="lgtm-hq/lgtm-ci" \
		GITHUB_RUN_ID="12345" \
		GITHUB_SHA="abc123" \
		bash "${PROJECT_ROOT}/scripts/ci/actions/generate-shell-test-comment.sh"

	assert_success
	assert_output --partial "Shell Tests Report"
	assert_output --partial "reusable test workflow"
	assert_output --partial "Status: ✅ PASSED"
	assert_output --partial "Coverage:"
	assert_output --partial "Test Results"
	assert_output --partial "Code Coverage"
	assert_output --partial "View full build details"
	assert_output --partial "Generated by Shell Tests workflow"
}

@test "generate-shell-test-comment: supports custom suite names and file output" {
	local comment_file="$BATS_TEST_TMPDIR/comment.md"

	run env \
		TEST_SUITE_NAME="Python Tests" \
		TESTS_PASSED="7" \
		TESTS_FAILED="0" \
		TESTS_TOTAL="7" \
		COVERAGE_PERCENT="88" \
		COVERAGE_THRESHOLD="80" \
		JOB_RESULT="success" \
		COMMENT_OUTPUT="$comment_file" \
		bash "${PROJECT_ROOT}/scripts/ci/actions/generate-shell-test-comment.sh"

	assert_success
	assert_file_exists "$comment_file"
	assert_file_contains "$comment_file" "Python Tests Report"
	assert_file_contains "$comment_file" "Generated by Python Tests workflow"
}
