#!/usr/bin/env bats
# SPDX-License-Identifier: MIT
# Purpose: Tests for scripts/ci/actions/generate-lighthouse-comment.sh

load "../../../helpers/common"

setup() {
	setup_temp_dir
	export GITHUB_OUTPUT="${BATS_TEST_TMPDIR}/github-output"
	touch "$GITHUB_OUTPUT"
}

teardown() {
	teardown_temp_dir
}

write_lighthouse_fixture() {
	local file="$1"
	local performance="$2"
	cat >"$file" <<EOF
{
  "categories": {
    "performance": {"score": ${performance}},
    "accessibility": {"score": 1},
    "best-practices": {"score": 0.96},
    "seo": {"score": 1}
  }
}
EOF
}

@test "generate-lighthouse-comment: uses unified report style when passing" {
	local results_file="${BATS_TEST_TMPDIR}/lighthouse.json"
	write_lighthouse_fixture "$results_file" "0.91"

	run env \
		GITHUB_OUTPUT="$GITHUB_OUTPUT" \
		RESULTS_PATH="$results_file" \
		REPORT_URL="https://example.com/lighthouse/" \
		THRESHOLD_PERFORMANCE="80" \
		THRESHOLD_ACCESSIBILITY="90" \
		THRESHOLD_BEST_PRACTICES="80" \
		THRESHOLD_SEO="80" \
		GITHUB_SERVER_URL="https://github.com" \
		GITHUB_REPOSITORY="lgtm-hq/lgtm-ci" \
		GITHUB_RUN_ID="12345" \
		GITHUB_SHA="abc123" \
		bash "${PROJECT_ROOT}/scripts/ci/actions/generate-lighthouse-comment.sh"

	assert_success
	assert_file_contains "$GITHUB_OUTPUT" "performance=91"
	assert_file_contains "$GITHUB_OUTPUT" "accessibility=100"
	assert_file_contains "$GITHUB_OUTPUT" "best-practices=96"
	assert_file_contains "$GITHUB_OUTPUT" "seo=100"
	assert_file_contains "$GITHUB_OUTPUT" "passed=true"
	assert_file_contains "$GITHUB_OUTPUT" "Lighthouse CI Performance Report"
	assert_file_contains "$GITHUB_OUTPUT" "Lighthouse CI performance workflow"
	assert_file_contains "$GITHUB_OUTPUT" "Status: ✅ PASSED"
	assert_file_contains "$GITHUB_OUTPUT" "Performance Scores"
	assert_file_contains "$GITHUB_OUTPUT" "View Lighthouse Reports"
	assert_file_contains "$GITHUB_OUTPUT" "View full build details"
	assert_file_contains "$GITHUB_OUTPUT" "Generated by lgtm-ci Lighthouse CI workflow"
}

@test "generate-lighthouse-comment: preserves threshold failure messaging" {
	local results_file="${BATS_TEST_TMPDIR}/lighthouse.json"
	write_lighthouse_fixture "$results_file" "0.50"

	run env \
		GITHUB_OUTPUT="$GITHUB_OUTPUT" \
		RESULTS_PATH="$results_file" \
		THRESHOLD_PERFORMANCE="80" \
		THRESHOLD_ACCESSIBILITY="90" \
		THRESHOLD_BEST_PRACTICES="80" \
		THRESHOLD_SEO="80" \
		bash "${PROJECT_ROOT}/scripts/ci/actions/generate-lighthouse-comment.sh"

	assert_success
	assert_file_contains "$GITHUB_OUTPUT" "performance=50"
	assert_file_contains "$GITHUB_OUTPUT" "passed=false"
	assert_file_contains "$GITHUB_OUTPUT" "Status: ⚠️ BELOW TARGET"
	assert_file_contains "$GITHUB_OUTPUT" "Some scores are below thresholds"
}
