name: 'Generate Lighthouse Comment'
description: 'Generate a formatted PR comment from Lighthouse CI results'
author: 'lgtm-hq'

inputs:
  results-path:
    description: 'Path to Lighthouse results JSON file or directory'
    required: true
  report-url:
    description: 'URL to full Lighthouse report (e.g., GitHub Pages URL)'
    required: false
    default: ''
  threshold-performance:
    description: 'Minimum performance score (0-100)'
    required: false
    default: '80'
  threshold-accessibility:
    description: 'Minimum accessibility score (0-100)'
    required: false
    default: '90'
  threshold-best-practices:
    description: 'Minimum best practices score (0-100)'
    required: false
    default: '80'
  threshold-seo:
    description: 'Minimum SEO score (0-100)'
    required: false
    default: '80'

outputs:
  comment-body:
    description: 'Generated comment body in Markdown'
    value: ${{ steps.generate.outputs.body }}
  performance-score:
    description: 'Performance score'
    value: ${{ steps.generate.outputs.performance }}
  accessibility-score:
    description: 'Accessibility score'
    value: ${{ steps.generate.outputs.accessibility }}
  best-practices-score:
    description: 'Best practices score'
    value: ${{ steps.generate.outputs.best-practices }}
  seo-score:
    description: 'SEO score'
    value: ${{ steps.generate.outputs.seo }}
  passed:
    description: 'Whether all scores meet thresholds'
    value: ${{ steps.generate.outputs.passed }}

runs:
  using: 'composite'
  steps:
    - name: Generate comment
      id: generate
      shell: bash
      run: |
        RESULTS_PATH="${{ inputs['results-path'] }}"
        REPORT_URL="${{ inputs['report-url'] }}"

        # Find the results file
        if [[ -d "$RESULTS_PATH" ]]; then
          RESULTS_FILE=$(find "$RESULTS_PATH" -name "*.json" -type f | head -1)
        else
          RESULTS_FILE="$RESULTS_PATH"
        fi

        if [[ ! -f "$RESULTS_FILE" ]]; then
          echo "::error::Lighthouse results not found at $RESULTS_PATH"
          exit 1
        fi

        # Extract scores (multiply by 100 for percentage)
        PERF=$(jq -r '.categories.performance.score // 0 | . * 100 | floor' "$RESULTS_FILE")
        A11Y=$(jq -r '.categories.accessibility.score // 0 | . * 100 | floor' "$RESULTS_FILE")
        BP=$(jq -r '.categories["best-practices"].score // 0 | . * 100 | floor' "$RESULTS_FILE")
        SEO=$(jq -r '.categories.seo.score // 0 | . * 100 | floor' "$RESULTS_FILE")

        echo "performance=$PERF" >> "$GITHUB_OUTPUT"
        echo "accessibility=$A11Y" >> "$GITHUB_OUTPUT"
        echo "best-practices=$BP" >> "$GITHUB_OUTPUT"
        echo "seo=$SEO" >> "$GITHUB_OUTPUT"

        # Check thresholds
        PASSED=true
        PERF_TH="${{ inputs['threshold-performance'] }}"
        A11Y_TH="${{ inputs['threshold-accessibility'] }}"
        BP_TH="${{ inputs['threshold-best-practices'] }}"
        SEO_TH="${{ inputs['threshold-seo'] }}"

        [[ $PERF -lt $PERF_TH ]] && PASSED=false
        [[ $A11Y -lt $A11Y_TH ]] && PASSED=false
        [[ $BP -lt $BP_TH ]] && PASSED=false
        [[ $SEO -lt $SEO_TH ]] && PASSED=false

        echo "passed=$PASSED" >> "$GITHUB_OUTPUT"

        # Helper function for score emoji
        score_emoji() {
          local score=$1
          local threshold=$2
          if [[ $score -ge 90 ]]; then
            echo "🟢"
          elif [[ $score -ge $threshold ]]; then
            echo "🟡"
          else
            echo "🔴"
          fi
        }

        # Generate comment body
        BODY="## Lighthouse Results

        | Category | Score | Threshold |
        |----------|-------|-----------|
        | $(score_emoji $PERF $PERF_TH) Performance | **${PERF}** | ${PERF_TH} |
        | $(score_emoji $A11Y $A11Y_TH) Accessibility | **${A11Y}** | ${A11Y_TH} |
        | $(score_emoji $BP $BP_TH) Best Practices | **${BP}** | ${BP_TH} |
        | $(score_emoji $SEO $SEO_TH) SEO | **${SEO}** | ${SEO_TH} |
        "

        if [[ -n "$REPORT_URL" ]]; then
          BODY="${BODY}

        [View Full Report](${REPORT_URL})"
        fi

        if [[ "$PASSED" == "true" ]]; then
          BODY="${BODY}

        ✅ All scores meet thresholds"
        else
          BODY="${BODY}

        ⚠️ Some scores are below thresholds"
        fi

        # Output body (handle multiline)
        EOF_MARKER="EOF_$(date +%s)"
        echo "body<<$EOF_MARKER" >> "$GITHUB_OUTPUT"
        echo "$BODY" >> "$GITHUB_OUTPUT"
        echo "$EOF_MARKER" >> "$GITHUB_OUTPUT"

branding:
  icon: 'zap'
  color: 'orange'
