---
name: 'Setup Environment'
description: 'Configure common CI environment variables and PATH'
author: 'lgtm-hq'

inputs:
  bin-dir:
    description: 'Directory for installed binaries (added to PATH)'
    required: false
    default: '${{ github.workspace }}/.local/bin'
  add-to-path:
    description: 'Additional directories to add to PATH (comma-separated)'
    required: false
    default: ''

outputs:
  bin-dir:
    description: 'The configured binary directory'
    value: ${{ inputs.bin-dir }}
  platform:
    description: 'Detected platform (linux-x86_64, darwin-arm64, etc.)'
    value: ${{ steps.setup.outputs.platform }}
  os:
    description: 'Detected OS (linux, darwin, windows)'
    value: ${{ steps.setup.outputs.os }}
  arch:
    description: 'Detected architecture (x86_64, arm64)'
    value: ${{ steps.setup.outputs.arch }}

runs:
  using: 'composite'
  steps:
    - name: Setup environment
      id: setup
      shell: bash
      env:
        BIN_DIR: ${{ inputs['bin-dir'] }}
        ADD_TO_PATH: ${{ inputs['add-to-path'] }}
      run: ${{ github.action_path }}/../../../scripts/ci/actions/setup-env.sh

branding:
  icon: 'settings'
  color: 'blue'
