name: 'Setup Python'
description: 'Setup Python with uv package manager and caching'
author: 'lgtm-hq'

inputs:
  python-version:
    description: 'Python version to install (e.g., "3.11", "3.12")'
    required: false
    default: '3.12'
  uv-version:
    description: 'uv version to install (e.g., "0.4.0", "latest")'
    required: false
    default: 'latest'
  cache:
    description: 'Enable uv cache'
    required: false
    default: 'true'
  cache-dependency-path:
    description: 'Path to dependency files for cache key (supports glob)'
    required: false
    default: |
      **/pyproject.toml
      **/requirements*.txt
      **/uv.lock
  working-directory:
    description: 'Working directory for uv commands'
    required: false
    default: '.'
  install-dependencies:
    description: 'Run uv sync to install dependencies'
    required: false
    default: 'true'

outputs:
  python-version:
    description: 'Installed Python version'
    value: ${{ steps.python-version.outputs.version }}
  uv-version:
    description: 'Installed uv version'
    value: ${{ steps.uv-version.outputs.version }}
  cache-hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5.1.0
      with:
        version: ${{ inputs.uv-version }}
        # Disable setup-uv's cache - we use actions/cache below to also cache .venv
        enable-cache: false

    - name: Get uv version
      id: uv-version
      shell: bash
      run: |
        version=$(uv --version | awk '{print $2}')
        echo "version=$version" >> "$GITHUB_OUTPUT"
        echo "uv version: $version"

    - name: Setup Python
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        uv python install "${{ inputs.python-version }}"
        echo "Python ${{ inputs.python-version }} installed"

    - name: Get Python version
      id: python-version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        version=$(uv run python --version | awk '{print $2}')
        echo "version=$version" >> "$GITHUB_OUTPUT"
        echo "Python version: $version"

    - name: Cache uv dependencies
      if: inputs.cache == 'true'
      id: cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ~/.cache/uv
          ${{ inputs.working-directory }}/.venv
        key: uv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles(inputs.cache-dependency-path) }}
        restore-keys: |
          uv-${{ runner.os }}-${{ inputs.python-version }}-
          uv-${{ runner.os }}-

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [[ -f "pyproject.toml" ]] || [[ -f "uv.lock" ]]; then
          echo "Installing dependencies with uv sync..."
          uv sync
        elif [[ -f "requirements.txt" ]]; then
          echo "Installing from requirements.txt..."
          uv pip install -r requirements.txt
        else
          echo "No dependency file found, skipping install"
        fi

branding:
  icon: 'code'
  color: 'yellow'
