#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Purpose: Generate aggregated PR comment for Rust test/clippy/fmt checks
#
# Environment variables:
#   TESTS_PASSED, TESTS_FAILED, TESTS_TOTAL - cargo test counts
#   TEST_RESULT, CLIPPY_RESULT, FMT_RESULT - job results (success/failure/skipped)
#   TEST_SUITE_NAME - Display name (default: Rust Checks)
#   COMMENT_OUTPUT - Output file path (default: rust-checks-pr-comment.md)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE:-$0}")" && pwd)"
LIB_DIR="$SCRIPT_DIR/../lib"

if [[ -f "$LIB_DIR/github/format.sh" ]]; then
	# shellcheck source=../lib/github/format.sh
	source "$LIB_DIR/github/format.sh"
fi

TESTS_PASSED="${TESTS_PASSED:-0}"
TESTS_FAILED="${TESTS_FAILED:-0}"
TESTS_TOTAL="${TESTS_TOTAL:-0}"
TEST_RESULT="${TEST_RESULT:-unknown}"
CLIPPY_RESULT="${CLIPPY_RESULT:-skipped}"
FMT_RESULT="${FMT_RESULT:-skipped}"
TEST_SUITE_NAME="${TEST_SUITE_NAME:-Rust Checks}"
COMMENT_OUTPUT="${COMMENT_OUTPUT:-rust-checks-pr-comment.md}"

sanitize_int() {
	local value="$1"
	value="${value//[^0-9]/}"
	if [[ -z "$value" ]]; then
		echo "0"
	else
		echo "$value"
	fi
}

TESTS_PASSED="$(sanitize_int "$TESTS_PASSED")"
TESTS_FAILED="$(sanitize_int "$TESTS_FAILED")"
TESTS_TOTAL="$(sanitize_int "$TESTS_TOTAL")"

result_emoji() {
	case "$1" in
	success) echo "✅" ;;
	failure) echo "❌" ;;
	skipped) echo "⏭️" ;;
	*) echo "⚠️" ;;
	esac
}

result_label() {
	case "$1" in
	success) echo "Passed" ;;
	failure) echo "Failed" ;;
	skipped) echo "Skipped" ;;
	cancelled) echo "Cancelled" ;;
	*) echo "Unknown" ;;
	esac
}

overall_failed="false"
if [[ "$TEST_RESULT" == "failure" ]] || [[ "$CLIPPY_RESULT" == "failure" ]] || [[ "$FMT_RESULT" == "failure" ]]; then
	overall_failed="true"
fi

if [[ "$overall_failed" == "true" ]]; then
	STATUS_EMOJI="❌"
	STATUS_TEXT="FAILED"
elif [[ "$TEST_RESULT" == "success" ]] &&
	{ [[ "$CLIPPY_RESULT" == "success" ]] || [[ "$CLIPPY_RESULT" == "skipped" ]]; } &&
	{ [[ "$FMT_RESULT" == "success" ]] || [[ "$FMT_RESULT" == "skipped" ]]; }; then
	STATUS_EMOJI="✅"
	STATUS_TEXT="PASSED"
else
	STATUS_EMOJI="⚠️"
	STATUS_TEXT="UNKNOWN"
fi

if [[ "$TESTS_TOTAL" -gt 0 ]]; then
	PASS_RATE=$((TESTS_PASSED * 100 / TESTS_TOTAL))
else
	PASS_RATE=0
fi

BUILD_URL=""
if declare -f get_github_actions_run_url &>/dev/null; then
	BUILD_URL=$(get_github_actions_run_url || true)
fi

COMMIT_LINE="- **Commit:** unknown"
if declare -f format_github_commit_line &>/dev/null; then
	COMMIT_LINE=$(format_github_commit_line)
fi

BUILD_LINK_BLOCK=""
if [[ -n "$BUILD_URL" ]]; then
	BUILD_LINK_BLOCK="

---

[View full build details](${BUILD_URL})"
fi

TEST_EMOJI="$(result_emoji "$TEST_RESULT")"
CLIPPY_EMOJI="$(result_emoji "$CLIPPY_RESULT")"
FMT_EMOJI="$(result_emoji "$FMT_RESULT")"

COMMENT_BODY="$(
	cat <<EOF
## 🦀 ${TEST_SUITE_NAME} Report

This PR has been analyzed using **lgtm-ci** reusable Rust checks.

### 📊 Status: ${STATUS_EMOJI} ${STATUS_TEXT}

| Check | Result |
|-------|--------|
| **cargo test** | ${TEST_EMOJI} $(result_label "$TEST_RESULT") |
| **cargo clippy** | ${CLIPPY_EMOJI} $(result_label "$CLIPPY_RESULT") |
| **cargo fmt --check** | ${FMT_EMOJI} $(result_label "$FMT_RESULT") |

### 🧪 Test Results

| Metric | Value |
|--------|-------|
| **Total Tests** | ${TESTS_TOTAL} |
| **Passed** | ${TESTS_PASSED} ✅ |
| **Failed** | ${TESTS_FAILED} |
| **Pass Rate** | ${PASS_RATE}% |

${COMMIT_LINE}
${BUILD_LINK_BLOCK}

<sub>Generated by ${TEST_SUITE_NAME} workflow</sub>
EOF
)"

printf '%s\n' "$COMMENT_BODY" >"$COMMENT_OUTPUT"
