#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Purpose: Generate coverage test summary markdown from coverage results
#
# Required environment variables:
#   COVERAGE_FILE - Path to coverage summary JSON file
#   FORMAT - Coverage format: istanbul, coverage-py, cobertura, lcov, or auto
#   REPORT_URL - URL to full report (optional)
#   THRESHOLD_LINES - Minimum line coverage percentage
#   THRESHOLD_BRANCHES - Minimum branch coverage percentage
#   THRESHOLD_FUNCTIONS - Minimum function coverage percentage

set -euo pipefail

# Source shared libraries for score_emoji and output helpers
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE:-$0}")" && pwd)"
LIB_DIR="$SCRIPT_DIR/../lib"

if [[ -f "$LIB_DIR/github/format.sh" ]]; then
	# shellcheck source=../lib/github/format.sh
	source "$LIB_DIR/github/format.sh"
fi

if [[ -f "$LIB_DIR/github/output.sh" ]]; then
	# shellcheck source=../lib/github/output.sh
	source "$LIB_DIR/github/output.sh"
fi

if [[ -f "$LIB_DIR/testing/coverage/extract.sh" ]]; then
	# shellcheck source=../lib/testing/coverage/extract.sh
	source "$LIB_DIR/testing/coverage/extract.sh"
fi

: "${COVERAGE_FILE:=coverage/coverage-summary.json}"
: "${FORMAT:=auto}"
: "${REPORT_URL:=}"
: "${THRESHOLD_LINES:=80}"
: "${THRESHOLD_BRANCHES:=70}"
: "${THRESHOLD_FUNCTIONS:=80}"
: "${TEST_SUITE_NAME:=}"

if [[ -n "$TEST_SUITE_NAME" ]]; then
	COVERAGE_HEADING="## 📊 Code Coverage Report — ${TEST_SUITE_NAME}"
else
	COVERAGE_HEADING="## 📊 Code Coverage Report"
fi

GENERATED_DATE=$(date -u +%Y-%m-%d)
COMMIT_LINE="- **Commit:** unknown"
if declare -f format_github_commit_line &>/dev/null; then
	COMMIT_LINE=$(format_github_commit_line)
fi
BUILD_URL=""
if declare -f get_github_actions_run_url &>/dev/null; then
	BUILD_URL=$(get_github_actions_run_url || true)
fi

# Check if coverage file exists
if [[ ! -f "$COVERAGE_FILE" ]]; then
	echo "::warning::Coverage file not found at $COVERAGE_FILE"
	BODY="${COVERAGE_HEADING}

This PR has been analyzed using **lgtm-ci** - our unified code coverage workflow.

### 📊 Status: ⚠️ MISSING

**Build:** ⚠️ No coverage data found

**Coverage:** ⚪ 0%

**Status:** Coverage report was not generated.

### 📊 Coverage Details

| Metric | Coverage | Threshold |
|--------|----------|-----------|
| **Lines** | 0% | ${THRESHOLD_LINES}% |
| **Branches** | 0% | ${THRESHOLD_BRANCHES}% |
| **Functions** | 0% | ${THRESHOLD_FUNCTIONS}% |
| **Statements** | 0% | - |

### 📋 Report Details
- **Generated:** ${GENERATED_DATE}
${COMMIT_LINE}"

	if [[ -n "$BUILD_URL" ]]; then
		BODY="${BODY}

---

[View full build details](${BUILD_URL})"
	fi

	BODY="${BODY}

<sub>Generated by lgtm-ci coverage workflow</sub>"

	{
		echo "lines=0"
		echo "branches=0"
		echo "functions=0"
		echo "statements=0"
		echo "passed=false"
	} >>"$GITHUB_OUTPUT"
	if declare -f set_github_output_multiline &>/dev/null; then
		set_github_output_multiline "body" "$BODY"
	else
		EOF_MARKER="EOF_MISSING"
		{
			echo "body<<$EOF_MARKER"
			echo "$BODY"
			echo "$EOF_MARKER"
		} >>"$GITHUB_OUTPUT"
	fi
	exit 0
fi

# Auto-detect format
if [[ "$FORMAT" == "auto" ]]; then
	if jq -e '.total' "$COVERAGE_FILE" >/dev/null 2>&1; then
		FORMAT="istanbul"
	elif jq -e '.totals' "$COVERAGE_FILE" >/dev/null 2>&1; then
		FORMAT="coverage-py"
	elif declare -f detect_coverage_format &>/dev/null; then
		case "$(detect_coverage_format "$COVERAGE_FILE")" in
		lcov) FORMAT="lcov" ;;
		cobertura) FORMAT="cobertura" ;;
		coverage-py) FORMAT="coverage-py" ;;
		istanbul) FORMAT="istanbul" ;;
		*) FORMAT="istanbul" ;;
		esac
	else
		FORMAT="istanbul"
	fi
fi

# Extract coverage based on format (raw float values)
case "$FORMAT" in
istanbul)
	LINES_RAW=$(jq -r '.total.lines.pct // 0' "$COVERAGE_FILE")
	BRANCHES_RAW=$(jq -r '.total.branches.pct // 0' "$COVERAGE_FILE")
	FUNCTIONS_RAW=$(jq -r '.total.functions.pct // 0' "$COVERAGE_FILE")
	STATEMENTS_RAW=$(jq -r '.total.statements.pct // 0' "$COVERAGE_FILE")
	;;
coverage-py)
	LINES_RAW=$(jq -r '.totals.percent_covered // 0' "$COVERAGE_FILE")
	BRANCHES_RAW=$(jq -r '.totals.percent_covered_branches // .totals.percent_covered // 0' "$COVERAGE_FILE")
	FUNCTIONS_RAW=$LINES_RAW # Python coverage doesn't track functions separately
	STATEMENTS_RAW=$LINES_RAW
	;;
lcov)
	if ! declare -f extract_coverage_details &>/dev/null; then
		echo "::error::LCOV support requires scripts/ci/lib/testing/coverage/extract.sh"
		exit 1
	fi
	extract_coverage_details "$COVERAGE_FILE"
	LINES_RAW=${COVERAGE_LINES:-0}
	BRANCHES_RAW=${COVERAGE_BRANCHES:-0}
	FUNCTIONS_RAW=${COVERAGE_FUNCTIONS:-0}
	STATEMENTS_RAW=${COVERAGE_STATEMENTS:-$LINES_RAW}
	;;
cobertura)
	if ! declare -f extract_coverage_details &>/dev/null; then
		echo "::error::Cobertura support requires scripts/ci/lib/testing/coverage/extract.sh"
		exit 1
	fi
	extract_coverage_details "$COVERAGE_FILE"
	LINES_RAW=${COVERAGE_LINES:-0}
	BRANCHES_RAW=${COVERAGE_BRANCHES:-0}
	FUNCTIONS_RAW=$LINES_RAW # Cobertura XML only exposes line/branch rates
	STATEMENTS_RAW=$LINES_RAW
	;;
*)
	echo "::error::Unknown coverage format: $FORMAT"
	exit 1
	;;
esac

# Check thresholds using raw float values to avoid false positives from rounding
# Use awk for float comparison (POSIX-compatible)
PASSED=true
if ! awk -v val="$LINES_RAW" -v thresh="$THRESHOLD_LINES" 'BEGIN { exit !(val >= thresh) }'; then
	PASSED=false
fi
if ! awk -v val="$BRANCHES_RAW" -v thresh="$THRESHOLD_BRANCHES" 'BEGIN { exit !(val >= thresh) }'; then
	PASSED=false
fi
if ! awk -v val="$FUNCTIONS_RAW" -v thresh="$THRESHOLD_FUNCTIONS" 'BEGIN { exit !(val >= thresh) }'; then
	PASSED=false
fi

# Round to integers for display
LINES=$(printf "%.0f" "$LINES_RAW")
BRANCHES=$(printf "%.0f" "$BRANCHES_RAW")
FUNCTIONS=$(printf "%.0f" "$FUNCTIONS_RAW")
STATEMENTS=$(printf "%.0f" "$STATEMENTS_RAW")

{
	echo "lines=$LINES"
	echo "branches=$BRANCHES"
	echo "functions=$FUNCTIONS"
	echo "statements=$STATEMENTS"
} >>"$GITHUB_OUTPUT"

# Output pass status (grouped with metrics above if needed)
{
	echo "passed=$PASSED"
} >>"$GITHUB_OUTPUT"

# Fallback score_emoji if library not available
if ! declare -f score_emoji &>/dev/null; then
	score_emoji() {
		local score=$1
		local threshold=$2
		local warn=$((threshold - 10))
		((warn < 0)) && warn=0
		if [[ $score -ge $threshold ]]; then
			echo "🟢"
		elif [[ $score -ge $warn ]]; then
			echo "🟡"
		else echo "🔴"; fi
	}
fi

# Generate comment body
COVERAGE_EMOJI=$(score_emoji "$LINES" "$THRESHOLD_LINES")
if [[ "$PASSED" == "true" ]]; then
	STATUS_EMOJI="✅"
	STATUS_TEXT="PASSED"
	COVERAGE_STATUS="Target met (lines >= ${THRESHOLD_LINES}%, branches >= ${THRESHOLD_BRANCHES}%, functions >= ${THRESHOLD_FUNCTIONS}%)"
else
	STATUS_EMOJI="⚠️"
	STATUS_TEXT="BELOW TARGET"
	COVERAGE_STATUS="Coverage is below one or more thresholds."
fi

BODY="${COVERAGE_HEADING}

This PR has been analyzed using **lgtm-ci** - our unified code coverage workflow.

### 📊 Status: ${STATUS_EMOJI} ${STATUS_TEXT}

**Build:** ✅ Coverage report generated

**Coverage:** ${COVERAGE_EMOJI} ${LINES}%

**Status:** ${COVERAGE_STATUS}

### 📊 Coverage Details

| Metric | Coverage | Threshold |
|--------|----------|-----------|
| **Lines** | $(score_emoji "$LINES" "$THRESHOLD_LINES") ${LINES}% | ${THRESHOLD_LINES}% |
| **Branches** | $(score_emoji "$BRANCHES" "$THRESHOLD_BRANCHES") ${BRANCHES}% | ${THRESHOLD_BRANCHES}% |
| **Functions** | $(score_emoji "$FUNCTIONS" "$THRESHOLD_FUNCTIONS") ${FUNCTIONS}% | ${THRESHOLD_FUNCTIONS}% |
| **Statements** | ${STATEMENTS}% | - |

### 📋 Report Details
- **Generated:** ${GENERATED_DATE}
${COMMIT_LINE}"

if [[ -n "$REPORT_URL" ]]; then
	BODY="${BODY}

### 🔎 View Detailed Report

Direct Link: [HTML Coverage Report](${REPORT_URL})"
fi

if [[ -n "$BUILD_URL" ]]; then
	BODY="${BODY}

---

[View full build details](${BUILD_URL})"
fi

BODY="${BODY}

<sub>Generated by lgtm-ci coverage workflow</sub>"

# Output body using shared helper or fallback
if declare -f set_github_output_multiline &>/dev/null; then
	set_github_output_multiline "body" "$BODY"
else
	EOF_MARKER="EOF_$(date +%s)"
	{
		echo "body<<$EOF_MARKER"
		echo "$BODY"
		echo "$EOF_MARKER"
	} >>"$GITHUB_OUTPUT"
fi
