#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Purpose: Generate formatted PR comment from Playwright test results
#
# Required environment variables:
#   RESULTS_PATH - Path to Playwright JSON results file
#   REPORT_URL - URL to full report (optional)
#   SHOW_FAILED - Whether to show failed tests list
#   MAX_FAILED - Maximum number of failed tests to show

set -euo pipefail

# Source shared libraries for formatting and output helpers
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE:-$0}")" && pwd)"
LIB_DIR="$SCRIPT_DIR/../lib"

if [[ -f "$LIB_DIR/github/format.sh" ]]; then
	# shellcheck source=../lib/github/format.sh
	source "$LIB_DIR/github/format.sh"
fi

if [[ -f "$LIB_DIR/github/output.sh" ]]; then
	# shellcheck source=../lib/github/output.sh
	source "$LIB_DIR/github/output.sh"
fi

: "${RESULTS_PATH:=playwright-report/results.json}"
: "${REPORT_URL:=}"
: "${SHOW_FAILED:=true}"
: "${MAX_FAILED:=10}"

GENERATED_DATE=$(date -u +%Y-%m-%d)
COMMIT_LINE="- **Commit:** unknown"
if declare -f format_github_commit_line &>/dev/null; then
	COMMIT_LINE=$(format_github_commit_line)
fi
BUILD_URL=""
if declare -f get_github_actions_run_url &>/dev/null; then
	BUILD_URL=$(get_github_actions_run_url || true)
fi

# Check if results file exists
if [[ ! -f "$RESULTS_PATH" ]]; then
	echo "::warning::Playwright results not found at $RESULTS_PATH"
	BODY="## 🧪 Playwright E2E Test Report

This PR has been analyzed using **lgtm-ci** - our Playwright E2E test workflow.

### 📊 Status: ⚠️ MISSING

**Build:** ⚠️ No Playwright results found

**Status:** Playwright results were not generated.

### 🧪 Test Results

| Metric | Value |
|--------|-------|
| **Total Tests** | 0 |
| **Passed** | 0 |
| **Failed** | 0 |
| **Skipped** | 0 |
| **Pass Rate** | 0% |

### 📋 Report Details
- **Generated:** ${GENERATED_DATE}
${COMMIT_LINE}"

	if [[ -n "$BUILD_URL" ]]; then
		BODY="${BODY}

---

[View full build details](${BUILD_URL})"
	fi

	BODY="${BODY}

<sub>Generated by lgtm-ci Playwright E2E workflow</sub>"

	{
		echo "total=0"
		echo "passed=0"
		echo "failed=0"
		echo "skipped=0"
		echo "success=false"
	} >>"$GITHUB_OUTPUT"
	if declare -f set_github_output_multiline &>/dev/null; then
		set_github_output_multiline "body" "$BODY"
	else
		EOF_MARKER="EOF_MISSING"
		{
			echo "body<<$EOF_MARKER"
			echo "$BODY"
			echo "$EOF_MARKER"
		} >>"$GITHUB_OUTPUT"
	fi
	exit 0
fi

# Extract test counts from Playwright JSON report
if jq -e '.stats' "$RESULTS_PATH" >/dev/null 2>&1; then
	# Standard report format
	# Include timedOut and interrupted in FAILED count (these are test failures)
	# All fields default to 0 to handle missing stats gracefully
	TOTAL=$(jq -r '((.stats.expected // 0) + (.stats.unexpected // 0) + (.stats.flaky // 0) + (.stats.skipped // 0) + (.stats.timedOut // 0) + (.stats.interrupted // 0))' "$RESULTS_PATH")
	PASSED=$(jq -r '.stats.expected // 0' "$RESULTS_PATH")
	FAILED=$(jq -r '((.stats.unexpected // 0) + (.stats.timedOut // 0) + (.stats.interrupted // 0))' "$RESULTS_PATH")
	SKIPPED=$(jq -r '.stats.skipped // 0' "$RESULTS_PATH")
	FLAKY=$(jq -r '.stats.flaky // 0' "$RESULTS_PATH")
	DURATION=$(jq -r '.stats.duration // 0' "$RESULTS_PATH")
else
	# Fallback: count from suites
	# Include timedOut and interrupted statuses as failures
	TOTAL=$(jq '[.. | .tests? // [] | .[]] | length' "$RESULTS_PATH" 2>/dev/null || echo "0")
	PASSED=$(jq '[.. | .tests? // [] | .[] | select(.status == "passed")] | length' "$RESULTS_PATH" 2>/dev/null || echo "0")
	FAILED=$(jq '[.. | .tests? // [] | .[] | select(.status == "failed" or .status == "timedOut" or .status == "interrupted")] | length' "$RESULTS_PATH" 2>/dev/null || echo "0")
	SKIPPED=$(jq '[.. | .tests? // [] | .[] | select(.status == "skipped")] | length' "$RESULTS_PATH" 2>/dev/null || echo "0")
	FLAKY=0
	DURATION=0
fi

SUCCESS="true"
[[ $FAILED -gt 0 ]] && SUCCESS="false"

{
	echo "total=$TOTAL"
	echo "passed=$PASSED"
	echo "failed=$FAILED"
	echo "skipped=$SKIPPED"
	echo "success=$SUCCESS"
} >>"$GITHUB_OUTPUT"

# Calculate pass rate (use awk for float precision with small suites)
if [[ $TOTAL -gt 0 ]]; then
	PASS_RATE=$(awk -v p="$PASSED" -v t="$TOTAL" 'BEGIN { printf "%.1f", (p*100)/t }')
else
	PASS_RATE=0
fi

# Format duration
if [[ $DURATION -gt 0 ]]; then
	DURATION_SEC=$((DURATION / 1000))
	DURATION_STR="${DURATION_SEC}s"
else
	DURATION_STR="N/A"
fi

# Status emoji
if [[ "$SUCCESS" == "true" ]]; then
	STATUS_EMOJI="✅"
	STATUS_TEXT="PASSED"
	TEST_STATUS_TEXT="✅ Tests passed"
	FAILED_EMOJI=""
else
	STATUS_EMOJI="❌"
	STATUS_TEXT="FAILED"
	TEST_STATUS_TEXT="❌ ${FAILED} test(s) failed"
	FAILED_EMOJI="❌"
fi

# Generate comment body
BODY="## 🧪 Playwright E2E Test Report

This PR has been analyzed using **lgtm-ci** - our Playwright E2E test workflow.

### 📊 Status: ${STATUS_EMOJI} ${STATUS_TEXT}

**Build:** ${TEST_STATUS_TEXT}

**Status:** ${TEST_STATUS_TEXT}

### 🧪 Test Results

| Metric | Value |
|--------|-------|
| **Total Tests** | ${TOTAL} |
| **Passed** | ${PASSED} ✅ |
| **Failed** | ${FAILED} ${FAILED_EMOJI} |
| **Skipped** | ${SKIPPED} |
| **Flaky** | ${FLAKY:-0} |
| **Duration** | ${DURATION_STR} |
| **Pass Rate** | ${PASS_RATE}% |"

# Add failed tests list (include timedOut and interrupted to match FAILED count)
if [[ "$SHOW_FAILED" == "true" && $FAILED -gt 0 ]]; then
	FAILED_TESTS=$(jq -r "[.. | .tests? // [] | .[] | select(.status == \"failed\" or .status == \"timedOut\" or .status == \"interrupted\") | .title] | .[0:${MAX_FAILED}] | .[]" "$RESULTS_PATH" 2>/dev/null || echo "")
	if [[ -n "$FAILED_TESTS" ]]; then
		BODY="${BODY}

<details>
<summary>Failed Tests (showing up to ${MAX_FAILED})</summary>

\`\`\`
${FAILED_TESTS}
\`\`\`

</details>"
	fi
fi

if [[ -n "$REPORT_URL" ]]; then
	BODY="${BODY}

### 🔎 View Full Reports

Public Report:

- [View Playwright HTML Report](${REPORT_URL})"
fi

BODY="${BODY}

### 📋 Report Details
- **Generated:** ${GENERATED_DATE}
${COMMIT_LINE}"

if [[ -n "$BUILD_URL" ]]; then
	BODY="${BODY}

---

[View full build details](${BUILD_URL})"
fi

BODY="${BODY}

<sub>Generated by lgtm-ci Playwright E2E workflow</sub>"

# Output body using shared helper or fallback
if declare -f set_github_output_multiline &>/dev/null; then
	set_github_output_multiline "body" "$BODY"
else
	EOF_MARKER="EOF_$(date +%s)"
	{
		echo "body<<$EOF_MARKER"
		echo "$BODY"
		echo "$EOF_MARKER"
	} >>"$GITHUB_OUTPUT"
fi
