#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Purpose: Generate PR comment for lintro analysis results
#
# Environment variables expected:
#   LINTRO_OUTPUT - Path to lintro check output file
#   LINTRO_EXIT_CODE - Exit code from lintro check
#   GITHUB_RUN_ID - GitHub Actions run ID
#   GITHUB_REPOSITORY - Repository name
#   GITHUB_SERVER_URL - GitHub server URL

set -euo pipefail

# Source shared libraries
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="$SCRIPT_DIR/../lib"

if [[ -f "$LIB_DIR/github/format.sh" ]]; then
	# shellcheck source=../lib/github/format.sh
	source "$LIB_DIR/github/format.sh"
fi

if [[ -f "$LIB_DIR/github/output.sh" ]]; then
	# shellcheck source=../lib/github/output.sh
	source "$LIB_DIR/github/output.sh"
fi

# Defaults
LINTRO_OUTPUT="${LINTRO_OUTPUT:-chk-output.txt}"
LINTRO_EXIT_CODE="${LINTRO_EXIT_CODE:-0}"

# Determine status using score_emoji if available for consistency
if [[ "$LINTRO_EXIT_CODE" -eq 0 ]]; then
	STATUS_EMOJI="✅"
	STATUS_TEXT="PASSED"
else
	STATUS_EMOJI="⚠️"
	STATUS_TEXT="ISSUES FOUND"
fi

# Build URL (use safe default for GITHUB_REPOSITORY to avoid double slashes)
REPO="${GITHUB_REPOSITORY:-unknown/unknown}"
BUILD_URL="${GITHUB_SERVER_URL:-https://github.com}/${REPO}/actions/runs/${GITHUB_RUN_ID:-0}"

# Extract execution summary from output
SUMMARY=""
if [[ -f "$LINTRO_OUTPUT" ]]; then
	# Try to extract the EXECUTION SUMMARY section
	if grep -q "EXECUTION SUMMARY" "$LINTRO_OUTPUT"; then
		SUMMARY=$(sed -n '/EXECUTION SUMMARY/,/^$/p' "$LINTRO_OUTPUT" | head -50)
	else
		# Fallback to last 30 lines
		SUMMARY=$(tail -30 "$LINTRO_OUTPUT")
	fi
fi

# Generate comment
cat <<EOF
## Lintro Code Quality Analysis

This PR has been analyzed using **lintro** - our unified code quality tool.

### Status: ${STATUS_EMOJI} ${STATUS_TEXT}

**Workflow:**
1. Performed code quality checks with \`lintro check\`

### Results:
\`\`\`
${SUMMARY}
\`\`\`

---

[View full build details](${BUILD_URL})

<sub>Generated by lintro analysis workflow</sub>
EOF
