#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Purpose: Fetch PR changed files and generate a file breakdown PR comment
#
# STEP dispatch (set STEP env var):
#   fetch    - Fetch the PR changed-files payload via gh api --paginate
#     Required env: GH_TOKEN, PR_NUMBER, GITHUB_REPOSITORY, PR_FILES_JSON (output path)
#   generate - Render the markdown comment from the fetched JSON payload
#     Required env: PR_FILES_JSON (input path)
#     Optional env: COMMENT_OUTPUT (write to file; stdout when unset),
#       MAX_ROWS (detail rows cap, default 50),
#       GITHUB_RUN_ID, GITHUB_REPOSITORY, GITHUB_SERVER_URL (build link)

set -euo pipefail

# =============================================================================
# Step: fetch - Retrieve changed files for a PR as a single JSON array
# =============================================================================
step_fetch() {
	: "${GH_TOKEN:?GH_TOKEN is required}"
	: "${PR_NUMBER:?PR_NUMBER is required}"
	: "${GITHUB_REPOSITORY:?GITHUB_REPOSITORY is required}"
	: "${PR_FILES_JSON:?PR_FILES_JSON is required}"

	if ! [[ "$PR_NUMBER" =~ ^[0-9]+$ ]]; then
		echo "::error::PR_NUMBER must be numeric, got: ${PR_NUMBER}" >&2
		exit 1
	fi

	# --paginate emits one JSON array per page; merge them into a single array
	gh api --paginate \
		"repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}/files?per_page=100" |
		jq -s 'add // []' >"$PR_FILES_JSON"

	local count
	count=$(jq 'length' "$PR_FILES_JSON")
	echo "Fetched ${count} changed files for PR #${PR_NUMBER}"
}

# =============================================================================
# Step: generate - Render the markdown comment
# =============================================================================
step_generate() {
	: "${PR_FILES_JSON:?PR_FILES_JSON is required}"
	local max_rows="${MAX_ROWS:-50}"

	if [[ ! -f "$PR_FILES_JSON" ]]; then
		echo "::error::PR files payload not found: ${PR_FILES_JSON}" >&2
		exit 1
	fi
	if ! jq -e 'type == "array"' "$PR_FILES_JSON" >/dev/null 2>&1; then
		echo "::error::PR files payload is not a JSON array: ${PR_FILES_JSON}" >&2
		exit 1
	fi
	# Normalize: reject non-numeric/zero, strip leading zeros (jq --argjson
	# rejects "05"), and clamp to a hard cap so a huge max-rows cannot push
	# the rendered comment past GitHub's comment size limit.
	local max_rows_cap=500
	if ! [[ "$max_rows" =~ ^[0-9]+$ ]] || [[ "$max_rows" -eq 0 ]]; then
		max_rows=50
	else
		max_rows=$((10#$max_rows))
	fi
	if ((max_rows > max_rows_cap)); then
		max_rows=$max_rows_cap
	fi

	# Byte budget for the assembled comment body. GitHub rejects comment bodies
	# over ~65,536 characters; keep headroom below that so the row cap alone
	# cannot push a worst-case long-path PR past the limit and fail publish.
	local body_byte_budget=60000

	local repo build_url
	repo="${GITHUB_REPOSITORY:-unknown/unknown}"
	build_url="${GITHUB_SERVER_URL:-https://github.com}/${repo}/actions/runs/${GITHUB_RUN_ID:-0}"

	local total_files total_add total_del
	total_files=$(jq 'length' "$PR_FILES_JSON")
	total_add=$(jq '[.[].additions] | add // 0' "$PR_FILES_JSON")
	total_del=$(jq '[.[].deletions] | add // 0' "$PR_FILES_JSON")

	local body
	if [[ "$total_files" -eq 0 ]]; then
		body="$(
			cat <<EOF
## PR File Breakdown

No files changed.

---

[View full build details](${build_url})

<sub>Generated by file breakdown workflow</sub>
EOF
		)"
	else
		local status_line group_rows detail_rows
		status_line=$(jq -r \
			'group_by(.status) | map("\(length) \(.[0].status)") | join(", ")' \
			"$PR_FILES_JSON")

		# Group by top-level directory; files at the repo root group as (root)
		group_rows=$(jq -r '
			def esc: gsub("[\r\n]"; " ") | gsub("\\|"; "\\|") | gsub("`"; "");
			map(. + {
				group: (if (.filename | test("/"))
					then (.filename | split("/")[0] + "/")
					else "(root)" end)
			})
			| group_by(.group)
			| sort_by(-length, .[0].group)
			| .[]
			| "| `\(.[0].group | esc)` | \(length) | +\(map(.additions) | add // 0) | -\(map(.deletions) | add // 0) |"
		' "$PR_FILES_JSON")

		# Render each candidate detail row (bounded by the row cap) as a single
		# neutralized line so rows can be dropped one-by-one to fit the budget.
		local -a all_rows=()
		mapfile -t all_rows < <(jq -r --argjson max "$max_rows" '
			def esc: gsub("[\r\n]"; " ") | gsub("\\|"; "\\|") | gsub("`"; "");
			.[:$max][]
			| "| `\(.filename | esc)` | \(.status) | +\(.additions) | -\(.deletions) |"
		' "$PR_FILES_JSON")
		local candidate_rows=${#all_rows[@]}

		# Assemble the body showing the first <shown> detail rows. When rows are
		# hidden, the note explains why: <size_forced> distinguishes the byte
		# budget from the plain row cap.
		assemble_body() {
			local shown="$1" size_forced="$2"
			local detail_rows="" details_summary="Changed files" truncation_note=""
			if ((shown > 0)); then
				printf -v detail_rows '%s\n' "${all_rows[@]:0:shown}"
				detail_rows=${detail_rows%$'\n'}
			fi
			if ((shown < total_files)); then
				local remaining=$((total_files - shown))
				details_summary="Changed files (first ${shown} of ${total_files})"
				if ((size_forced)); then
					truncation_note=$'\n'"…and ${remaining} more file(s) not shown"
					truncation_note+=" (dropped to keep this comment within GitHub's size limit)."
				else
					truncation_note=$'\n'"…and ${remaining} more file(s) not shown."
				fi
			fi
			cat <<EOF
## PR File Breakdown

**${total_files} file(s) changed** (+${total_add} / -${total_del}) — ${status_line}

| Area | Files | Additions | Deletions |
| --- | ---: | ---: | ---: |
${group_rows}

<details>
<summary>${details_summary}</summary>

| File | Status | Additions | Deletions |
| --- | --- | ---: | ---: |
${detail_rows}
${truncation_note}

</details>

---

[View full build details](${build_url})

<sub>Generated by file breakdown workflow</sub>
EOF
		}

		# Start with the row-capped view, then shrink to satisfy the byte budget.
		local shown=$candidate_rows
		body="$(assemble_body "$shown" 0)"
		if (($(printf '%s' "$body" | wc -c) > body_byte_budget)); then
			# Binary search for the largest row count whose body fits the budget.
			local lo=0 hi=$((candidate_rows - 1)) best=0 mid trial
			while ((lo <= hi)); do
				mid=$(((lo + hi) / 2))
				trial="$(assemble_body "$mid" 1)"
				if (($(printf '%s' "$trial" | wc -c) <= body_byte_budget)); then
					best=$mid
					lo=$((mid + 1))
				else
					hi=$((mid - 1))
				fi
			done
			shown=$best
			body="$(assemble_body "$shown" 1)"
		fi
	fi

	if [[ -n "${COMMENT_OUTPUT:-}" ]]; then
		printf '%s\n' "$body" >"$COMMENT_OUTPUT"
	else
		printf '%s\n' "$body"
	fi
}

# =============================================================================
# Dispatch
# =============================================================================
STEP="${STEP:-generate}"
case "$STEP" in
fetch)
	step_fetch
	;;
generate)
	step_generate
	;;
*)
	echo "::error::Unknown STEP: ${STEP} (expected fetch or generate)" >&2
	exit 1
	;;
esac
