---
name: 'Post PR Comment'
description: >-
  Create or update a PR comment with unique marker for upsert behavior
author: 'lgtm-hq'

inputs:
  token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  pr-number:
    description: >-
      Pull request number (auto-detected from context if not provided)
    required: false
    default: ''
  marker:
    description: >-
      Unique marker to identify this comment for updates
    required: true
  body:
    description: 'Comment body content (Markdown supported)'
    required: true
  mode:
    description: >-
      Comment mode: upsert (create or update), create, or update
    required: false
    default: 'upsert'
  delete-on-empty:
    description: 'Delete existing comment if body is empty'
    required: false
    default: 'false'

outputs:
  comment-id:
    description: 'ID of the created or updated comment'
    value: ${{ steps.post.outputs.comment-id }}
  comment-url:
    description: 'URL of the comment'
    value: ${{ steps.post.outputs.comment-url }}
  action-taken:
    description: 'Action taken: "created", "updated", "deleted", or "skipped"'
    value: ${{ steps.post.outputs.action-taken }}

runs:
  using: 'composite'
  steps:
    - name: Determine PR number
      id: pr-number
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      # yamllint disable rule:line-length
      run: |
        PR_NUMBER="${{ inputs['pr-number'] }}"
        if [[ -z "$PR_NUMBER" ]]; then
          EVENT="${{ github.event_name }}"
          if [[ "$EVENT" == "pull_request" || "$EVENT" == "pull_request_target" ]]; then
            PR_NUMBER="${{ github.event.pull_request.number }}"
          elif [[ "$EVENT" == "issue_comment" ]]; then
            PR_NUMBER="${{ github.event.issue.number }}"
          else
            PR_NUMBER=$(gh pr view --json number -q '.number' 2>/dev/null || echo "")
          fi
        fi
        if [[ -z "$PR_NUMBER" ]]; then
          echo "::error::Could not determine PR number"
          exit 1
        fi
        echo "number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
      # yamllint enable rule:line-length

    - name: Post or update comment
      id: post
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        COMMENT_BODY: ${{ inputs.body }}
        PR_NUMBER: ${{ steps.pr-number.outputs.number }}
        MARKER: ${{ inputs.marker }}
        MODE: ${{ inputs.mode }}
        DELETE_ON_EMPTY: ${{ inputs['delete-on-empty'] }}
      run: >-
        ${{ github.action_path }}/../../../scripts/ci/actions/post-pr-comment.sh

branding:
  icon: 'message-square'
  color: 'blue'
