---
name: 'Run vitest'
description: 'Run JavaScript/TypeScript tests using vitest with coverage support'
author: 'lgtm-hq'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  test-path:
    description: 'Path to test files or directory'
    required: false
    default: '.'
  coverage:
    description: 'Whether to collect coverage (true/false)'
    required: false
    default: 'false'
  coverage-format:
    description: 'Coverage output format: json, lcov, html'
    required: false
    default: 'json'
  extra-args:
    description: 'Additional arguments to pass to vitest'
    required: false
    default: ''
  working-directory:
    description: 'Working directory for running tests'
    required: false
    default: '.'

outputs:
  exit-code:
    description: 'Exit code from vitest'
    value: ${{ steps.run.outputs.exit-code }}
  tests-passed:
    description: 'Number of tests passed'
    value: ${{ steps.parse.outputs.tests-passed }}
  tests-failed:
    description: 'Number of tests failed'
    value: ${{ steps.parse.outputs.tests-failed }}
  tests-skipped:
    description: 'Number of tests skipped'
    value: ${{ steps.parse.outputs.tests-skipped }}
  tests-total:
    description: 'Total number of tests'
    value: ${{ steps.parse.outputs.tests-total }}
  coverage-file:
    description: 'Path to coverage file'
    value: ${{ steps.run.outputs.coverage-file }}
  coverage-percent:
    description: 'Coverage percentage'
    value: ${{ steps.parse.outputs.coverage-percent }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: ./.github/actions/setup-node
      with:
        node-version: ${{ inputs.node-version }}
        working-directory: ${{ inputs.working-directory }}

    - name: Setup vitest
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        STEP: setup
        COVERAGE: ${{ inputs.coverage }}
      run: ${{ github.action_path }}/../../../scripts/ci/actions/run-vitest.sh

    - name: Run vitest
      id: run
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        STEP: run
        TEST_PATH: ${{ inputs.test-path }}
        COVERAGE: ${{ inputs.coverage }}
        COVERAGE_FORMAT: ${{ inputs.coverage-format }}
        EXTRA_ARGS: ${{ inputs.extra-args }}
      run: ${{ github.action_path }}/../../../scripts/ci/actions/run-vitest.sh
      continue-on-error: true

    - name: Parse results
      id: parse
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        STEP: parse
        RESULTS_FILE: vitest-results.json
        COVERAGE_FILE: ${{ steps.run.outputs.coverage-file }}
      run: ${{ github.action_path }}/../../../scripts/ci/actions/run-vitest.sh

    - name: Generate summary
      shell: bash
      env:
        STEP: summary
        TESTS_PASSED: ${{ steps.parse.outputs.tests-passed }}
        TESTS_FAILED: ${{ steps.parse.outputs.tests-failed }}
        TESTS_SKIPPED: ${{ steps.parse.outputs.tests-skipped }}
        TESTS_TOTAL: ${{ steps.parse.outputs.tests-total }}
        COVERAGE_PERCENT: ${{ steps.parse.outputs.coverage-percent }}
        EXIT_CODE: ${{ steps.run.outputs.exit-code }}
      run: ${{ github.action_path }}/../../../scripts/ci/actions/run-vitest.sh

    - name: Check test result
      if: steps.run.outputs.exit-code != '0'
      shell: bash
      run: exit ${{ steps.run.outputs.exit-code }}

branding:
  icon: 'check-circle'
  color: 'green'
